/* AUTO-GENERATED by scripts/gvi-build.mjs — DO NOT EDIT BY HAND.
   Edit data/gvi/latest.json (or run the ingest pipeline), then:
     node scripts/gvi-build.mjs
   Source data as of 2026-09-14. */
window.GVI_DATA = {
  "meta": {
    "brand": "FDK Velocity",
    "tagline": "The Velocity Edge · by FDK",
    "scale": "0–100",
    "source": "FDK Velocity Intelligence Platform",
    "updated": "2026-09-14"
  },
  "daily": {
    "index": {
      "label": "Global Velocity Index",
      "score": 107.3,
      "delta": 0.2,
      "deltaPct": "+0.19%",
      "trend": "up",
      "trend30d": "Accelerating",
      "asOf": "2026-07-29",
      "improving": 7,
      "declining": 0,
      "coverage": 15
    },
    "countries": {
      "asOf": "2026-07-29",
      "rows": [
        {
          "rank": 1,
          "flag": "🇺🇸",
          "name": "United States",
          "score": 93.4,
          "delta": 0.2,
          "trend": "up",
          "tag": "Accelerating",
          "spark": [
            92.1,
            92.3,
            92.4,
            92.6,
            92.8,
            93,
            93.2,
            93.4
          ]
        },
        {
          "rank": 2,
          "flag": "🇨🇳",
          "name": "China",
          "score": 91,
          "delta": 0.1,
          "trend": "up",
          "tag": "Accelerating strongly",
          "spark": [
            89.4,
            89.8,
            90.1,
            90.3,
            90.5,
            90.7,
            90.9,
            91
          ]
        },
        {
          "rank": 3,
          "flag": "🇰🇷",
          "name": "South Korea",
          "score": 87.8,
          "delta": 0.1,
          "trend": "up",
          "tag": "Accelerating very strongly",
          "spark": [
            86.2,
            86.6,
            87,
            87.2,
            87.4,
            87.5,
            87.7,
            87.8
          ]
        },
        {
          "rank": 4,
          "flag": "🇯🇵",
          "name": "Japan",
          "score": 84.9,
          "delta": 0,
          "trend": "up",
          "tag": "Accelerating",
          "spark": [
            84.1,
            84.3,
            84.5,
            84.6,
            84.7,
            84.8,
            84.9,
            84.9
          ]
        },
        {
          "rank": 5,
          "flag": "🇩🇪",
          "name": "Germany",
          "score": 82.8,
          "delta": 0,
          "trend": "up",
          "tag": "Improving",
          "spark": [
            82.4,
            82.5,
            82.6,
            82.6,
            82.7,
            82.7,
            82.8,
            82.8
          ]
        },
        {
          "rank": 6,
          "flag": "🇬🇧",
          "name": "United Kingdom",
          "score": 82.1,
          "delta": 0,
          "trend": "up",
          "tag": "Accelerating moderately",
          "spark": [
            81.6,
            81.7,
            81.8,
            81.9,
            82,
            82,
            82.1,
            82.1
          ]
        },
        {
          "rank": 7,
          "flag": "🇫🇷",
          "name": "France",
          "score": 81.6,
          "delta": 0,
          "trend": "up",
          "tag": "Accelerating strongly",
          "spark": [
            80.9,
            81.1,
            81.2,
            81.3,
            81.4,
            81.5,
            81.6,
            81.6
          ]
        },
        {
          "rank": 8,
          "flag": "🇨🇭",
          "name": "Switzerland",
          "score": 80.7,
          "delta": 0,
          "trend": "flat",
          "tag": "Stable-positive",
          "spark": [
            80.5,
            80.6,
            80.6,
            80.7,
            80.6,
            80.7,
            80.7,
            80.7
          ]
        },
        {
          "rank": 9,
          "flag": "🇳🇱",
          "name": "Netherlands",
          "score": 80.1,
          "delta": 0,
          "trend": "flat",
          "tag": "Stable",
          "spark": [
            80,
            80,
            80.1,
            80,
            80.1,
            80.1,
            80.1,
            80.1
          ]
        },
        {
          "rank": 10,
          "flag": "🇸🇪",
          "name": "Sweden",
          "score": 78.9,
          "delta": 0,
          "trend": "up",
          "tag": "Accelerating moderately",
          "spark": [
            78.3,
            78.5,
            78.6,
            78.7,
            78.8,
            78.8,
            78.9,
            78.9
          ]
        },
        {
          "rank": 11,
          "flag": "🇩🇰",
          "name": "Denmark",
          "score": 77.8,
          "delta": 0,
          "trend": "flat",
          "tag": "Stable-positive",
          "spark": [
            77.4,
            77.5,
            77.6,
            77.6,
            77.7,
            77.7,
            77.8,
            77.8
          ]
        },
        {
          "rank": 12,
          "flag": "🇳🇴",
          "name": "Norway",
          "score": 77.2,
          "delta": 0,
          "trend": "flat",
          "tag": "Stable-positive",
          "spark": [
            76.9,
            77,
            77,
            77.1,
            77.1,
            77.2,
            77.2,
            77.2
          ]
        },
        {
          "rank": 13,
          "flag": "🇪🇸",
          "name": "Spain",
          "score": 74.6,
          "delta": 0,
          "trend": "up",
          "tag": "Improving",
          "spark": [
            74.1,
            74.2,
            74.3,
            74.4,
            74.5,
            74.5,
            74.6,
            74.6
          ]
        },
        {
          "rank": 14,
          "flag": "🇦🇹",
          "name": "Austria",
          "score": 72.5,
          "delta": 0,
          "trend": "flat",
          "tag": "Stable",
          "spark": [
            72.3,
            72.3,
            72.4,
            72.4,
            72.5,
            72.5,
            72.5,
            72.5
          ]
        },
        {
          "rank": 15,
          "flag": "🇮🇹",
          "name": "Italy",
          "score": 71.8,
          "delta": 0,
          "trend": "up",
          "tag": "Improving slowly",
          "spark": [
            71.5,
            71.6,
            71.6,
            71.7,
            71.7,
            71.8,
            71.8,
            71.8
          ]
        }
      ]
    },
    "corporates": {
      "asOf": "2026-07-29",
      "average": {
        "score": 62.7,
        "delta": 0.2,
        "trend": "up"
      },
      "top": [
        {
          "rank": 1,
          "name": "NVIDIA",
          "sector": "Semiconductors / AI",
          "score": 96.8,
          "delta": 0.6,
          "trend": "up"
        },
        {
          "rank": 2,
          "name": "Microsoft",
          "sector": "Technology / Cloud",
          "score": 94.1,
          "delta": 0.4,
          "trend": "up"
        },
        {
          "rank": 3,
          "name": "Apple",
          "sector": "Technology",
          "score": 92.6,
          "delta": 0.3,
          "trend": "up"
        },
        {
          "rank": 4,
          "name": "Alphabet",
          "sector": "Technology / AI",
          "score": 90,
          "delta": 0.3,
          "trend": "up"
        },
        {
          "rank": 5,
          "name": "Amazon",
          "sector": "Cloud / E-commerce",
          "score": 88.3,
          "delta": 0.2,
          "trend": "up"
        },
        {
          "rank": 6,
          "name": "TSMC",
          "sector": "Semiconductors",
          "score": 87.4,
          "delta": 0.4,
          "trend": "up"
        },
        {
          "rank": 7,
          "name": "Broadcom",
          "sector": "Semiconductors",
          "score": 86.2,
          "delta": 0.5,
          "trend": "up"
        },
        {
          "rank": 8,
          "name": "Meta",
          "sector": "Social Media / AI",
          "score": 84.7,
          "delta": 0.4,
          "trend": "up"
        },
        {
          "rank": 9,
          "name": "ASML",
          "sector": "Semiconductor Equip.",
          "score": 83,
          "delta": 0,
          "trend": "flat"
        },
        {
          "rank": 10,
          "name": "Tesla",
          "sector": "Automotive / Energy",
          "score": 82.5,
          "delta": 0.1,
          "trend": "up"
        },
        {
          "rank": 11,
          "name": "Berkshire Hathaway",
          "sector": "Diversified",
          "score": 81.4,
          "delta": 0,
          "trend": "flat"
        },
        {
          "rank": 12,
          "name": "Eli Lilly",
          "sector": "Pharma / Biotech",
          "score": 80.3,
          "delta": 0.2,
          "trend": "up"
        },
        {
          "rank": 13,
          "name": "JPMorgan Chase",
          "sector": "Financials",
          "score": 79.1,
          "delta": 0,
          "trend": "flat"
        },
        {
          "rank": 14,
          "name": "Visa",
          "sector": "Payments Technology",
          "score": 78.5,
          "delta": 0.1,
          "trend": "up"
        },
        {
          "rank": 15,
          "name": "SAP",
          "sector": "Enterprise Software",
          "score": 77.3,
          "delta": 0.2,
          "trend": "up"
        }
      ],
      "bottom": [
        {
          "rank": 241,
          "name": "China Evergrande Group",
          "sector": "Real Estate",
          "score": 18,
          "delta": -0.2,
          "trend": "down"
        },
        {
          "rank": 242,
          "name": "Country Garden Holdings",
          "sector": "Real Estate",
          "score": 19.2,
          "delta": -0.2,
          "trend": "down"
        },
        {
          "rank": 243,
          "name": "Evergrande Property Svcs",
          "sector": "Real Estate Svcs",
          "score": 20.1,
          "delta": -0.2,
          "trend": "down"
        },
        {
          "rank": 244,
          "name": "Siemens Energy (legacy)",
          "sector": "Energy Equip.",
          "score": 21.5,
          "delta": -0.1,
          "trend": "down"
        },
        {
          "rank": 245,
          "name": "Credit Suisse Group (HL)",
          "sector": "Financials",
          "score": 22.7,
          "delta": -0.1,
          "trend": "down"
        },
        {
          "rank": 246,
          "name": "PayPal Holdings",
          "sector": "Fintech",
          "score": 23.9,
          "delta": -0.1,
          "trend": "down"
        },
        {
          "rank": 247,
          "name": "WeWork Inc.",
          "sector": "Real Estate Svcs",
          "score": 24.8,
          "delta": -0.2,
          "trend": "down"
        },
        {
          "rank": 248,
          "name": "Bed Bath & Beyond (NOL)",
          "sector": "Retail",
          "score": 25.3,
          "delta": -0.2,
          "trend": "down"
        },
        {
          "rank": 249,
          "name": "3M Company",
          "sector": "Industrials",
          "score": 25.9,
          "delta": -0.1,
          "trend": "down"
        },
        {
          "rank": 250,
          "name": "AMC Entertainment",
          "sector": "Entertainment",
          "score": 26.4,
          "delta": -0.1,
          "trend": "down"
        }
      ],
      "sectors": [
        {
          "rank": 1,
          "name": "Semiconductors",
          "score": 84.6,
          "delta": 0.4,
          "trend": "up"
        },
        {
          "rank": 2,
          "name": "Technology / Cloud",
          "score": 73.8,
          "delta": 0.3,
          "trend": "up"
        },
        {
          "rank": 3,
          "name": "Pharma / Biotech",
          "score": 69.1,
          "delta": 0.2,
          "trend": "up"
        },
        {
          "rank": 4,
          "name": "Payments / Fintech",
          "score": 66.2,
          "delta": 0.2,
          "trend": "up"
        },
        {
          "rank": 5,
          "name": "Aerospace & Defense",
          "score": 64.1,
          "delta": 0.1,
          "trend": "up"
        }
      ]
    }
  },
  "weekly": {
    "weekEnding": "2026-07-25",
    "countriesScorecard": {
      "weekEnding": "2026-07-25",
      "globalAverage": {
        "score": 68.6,
        "delta": 0.4
      },
      "topRankings": [
        {
          "rank": 1,
          "country": "United States",
          "score": 93.2,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 2,
          "country": "China",
          "score": 90.9,
          "weeklyDelta": 0,
          "trend": "up"
        },
        {
          "rank": 3,
          "country": "South Korea",
          "score": 87.5,
          "weeklyDelta": 0.2,
          "trend": "up"
        },
        {
          "rank": 4,
          "country": "Japan",
          "score": 84.9,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 5,
          "country": "Germany",
          "score": 82.8,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 6,
          "country": "United Kingdom",
          "score": 82.1,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 7,
          "country": "France",
          "score": 81.4,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 8,
          "country": "Switzerland",
          "score": 80.7,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 9,
          "country": "Netherlands",
          "score": 80.1,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 10,
          "country": "Sweden",
          "score": 78.9,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 11,
          "country": "Denmark",
          "score": 77.8,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 12,
          "country": "Norway",
          "score": 77.2,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 13,
          "country": "Spain",
          "score": 74.6,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 14,
          "country": "Austria",
          "score": 72.5,
          "weeklyDelta": 0,
          "trend": "flat"
        },
        {
          "rank": 15,
          "country": "Italy",
          "score": 71.8,
          "weeklyDelta": 0,
          "trend": "flat"
        }
      ],
      "bottomRankings": [
        {
          "rank": 76,
          "country": "South Africa",
          "score": 44.6
        },
        {
          "rank": 77,
          "country": "Argentina",
          "score": 43.7
        },
        {
          "rank": 78,
          "country": "Turkey",
          "score": 41.9
        },
        {
          "rank": 79,
          "country": "Egypt",
          "score": 40.8
        },
        {
          "rank": 80,
          "country": "Venezuela",
          "score": 38.1
        }
      ],
      "biggestImprovers": [
        {
          "country": "South Korea",
          "delta": 0.2
        },
        {
          "country": "China",
          "delta": 0.1
        },
        {
          "country": "Japan",
          "delta": 0.1
        },
        {
          "country": "Germany",
          "delta": 0.1
        },
        {
          "country": "Switzerland",
          "delta": 0
        }
      ],
      "regionalLeaders": [
        {
          "region": "North America",
          "country": "United States",
          "score": 93.2
        },
        {
          "region": "South America",
          "country": "Brazil",
          "score": 61
        },
        {
          "region": "Europe",
          "country": "Switzerland",
          "score": 80.7
        },
        {
          "region": "Asia",
          "country": "South Korea",
          "score": 87.5
        },
        {
          "region": "Middle East",
          "country": "United Arab Emirates",
          "score": 81
        },
        {
          "region": "Africa",
          "country": "Mauritius",
          "score": 58.2
        },
        {
          "region": "Oceania",
          "country": "Australia",
          "score": 72
        }
      ],
      "pillars": [
        {
          "name": "Intelligence Infrastructure",
          "score": 74.7,
          "delta": 0.3
        },
        {
          "name": "Innovation Velocity",
          "score": 72.1,
          "delta": 0.2
        },
        {
          "name": "Enterprise Transformation",
          "score": 71.9,
          "delta": 0.2
        },
        {
          "name": "Smart Capital",
          "score": 69.9,
          "delta": 0.1
        },
        {
          "name": "Discovery Capacity",
          "score": 67.8,
          "delta": 0.2
        },
        {
          "name": "Market Expansion",
          "score": 70.6,
          "delta": 0.2
        },
        {
          "name": "Policy & Sovereign Support",
          "score": 68.7,
          "delta": 0.1
        },
        {
          "name": "Supply-Chain Resilience",
          "score": 67.7,
          "delta": 0.1
        },
        {
          "name": "Talent Intensity",
          "score": 68.3,
          "delta": 0.1
        },
        {
          "name": "Strategic Optionality",
          "score": 70.9,
          "delta": 0.1
        }
      ],
      "keyNumbers": [
        {
          "value": "2.9%",
          "label": "Global Real GDP Growth Forecast 2026 (IMF Jul 2026)"
        },
        {
          "value": "5.2%",
          "label": "Global Inflation Forecast 2026 (IMF Jul 2026)"
        },
        {
          "value": "$9.7T",
          "label": "Global FDI Inflows 2026 Forecast (UNCTAD)"
        },
        {
          "value": "$110T+",
          "label": "Global Infrastructure Investment Need by 2040 (McKinsey)"
        },
        {
          "value": "+$180B",
          "label": "Global AI Private Investment in Q2 2026 (PitchBook NVCA)"
        }
      ]
    },
    "industries": {
      "weekEnding": "2026-07-25",
      "corporateAverageAllIndustries": {
        "score": 71.2,
        "delta": 0.5
      },
      "highestIndustry": {
        "name": "Technology Hardware",
        "score": 83.6
      },
      "lowestIndustry": {
        "name": "Real Estate",
        "score": 41.2
      },
      "industries": [
        {
          "rank": 1,
          "name": "Technology Hardware",
          "avgScore": 83.6,
          "weeklyDelta": 1.1,
          "top": [
            {
              "rank": 1,
              "company": "NVIDIA",
              "score": 94.8,
              "delta": 2.1,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "TSMC",
              "score": 92.7,
              "delta": 1.3,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "ASML",
              "score": 89.1,
              "delta": 0.9,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Broadcom",
              "score": 87.3,
              "delta": 0.8,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "SK Hynix",
              "score": 86.4,
              "delta": 1.4,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Microchip Tech",
              "score": 45.3,
              "delta": -0.6,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "GlobalFoundries",
              "score": 43.2,
              "delta": -0.4,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "ON Semiconductor",
              "score": 42.7,
              "delta": -0.4,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "SMIC",
              "score": 41.8,
              "delta": -0.6,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Intel (Foundry)",
              "score": 39.6,
              "delta": -1,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 2,
          "name": "Technology Software",
          "avgScore": 81.2,
          "weeklyDelta": 0.7,
          "top": [
            {
              "rank": 1,
              "company": "Microsoft",
              "score": 92.6,
              "delta": 1.1,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Salesforce",
              "score": 87.3,
              "delta": 0.8,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "SAP",
              "score": 86,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "ServiceNow",
              "score": 84.2,
              "delta": 0.7,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Adobe",
              "score": 82.1,
              "delta": 0.5,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Open Text",
              "score": 45.4,
              "delta": -0.5,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "IFS",
              "score": 43.1,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Sage Group",
              "score": 42.7,
              "delta": -0.4,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Dassault Systèmes (Legacy)",
              "score": 41.5,
              "delta": -0.4,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Micro Focus",
              "score": 39.8,
              "delta": -0.7,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 3,
          "name": "Financial Services",
          "avgScore": 72.8,
          "weeklyDelta": 0.2,
          "top": [
            {
              "rank": 1,
              "company": "JPMorgan Chase & Co.",
              "score": 87.9,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Visa",
              "score": 81.6,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Mastercard",
              "score": 79.8,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "UBS Group",
              "score": 78.2,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Goldman Sachs",
              "score": 76.3,
              "delta": 0.2,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Credit Suisse (Legacy)",
              "score": 40.2,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Comerica",
              "score": 38.7,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Zions Bancorporation",
              "score": 37.9,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "First Republic (Legacy)",
              "score": 36.5,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "SVB Financial (Legacy)",
              "score": 35.1,
              "delta": -0.3,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 4,
          "name": "Automotive",
          "avgScore": 68.4,
          "weeklyDelta": 0.4,
          "top": [
            {
              "rank": 1,
              "company": "Tesla",
              "score": 87.1,
              "delta": 0.8,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "BYD",
              "score": 82.3,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Toyota Motor",
              "score": 75.6,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "BMW Group",
              "score": 74.1,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Hyundai Motor",
              "score": 72.8,
              "delta": 0.4,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Nissan Motor",
              "score": 41.6,
              "delta": -0.4,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Stellantis",
              "score": 40.2,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Jaguar Land Rover",
              "score": 38.7,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Lucid Group",
              "score": 36.5,
              "delta": -0.6,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Faraday Future",
              "score": 34.1,
              "delta": -0.5,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 5,
          "name": "Pharmaceuticals",
          "avgScore": 74.6,
          "weeklyDelta": 0.3,
          "top": [
            {
              "rank": 1,
              "company": "Pfizer",
              "score": 85.1,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Roche",
              "score": 84.3,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Novartis",
              "score": 81.2,
              "delta": 0.5,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Eli Lilly",
              "score": 79.6,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Merck & Co.",
              "score": 78.1,
              "delta": 0.4,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Dr. Reddy's Labs",
              "score": 43.5,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Viatris",
              "score": 42.1,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Sun Pharma",
              "score": 41,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Lupin",
              "score": 39.4,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Bavarian Nordic",
              "score": 37.8,
              "delta": -0.2,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 6,
          "name": "Energy",
          "avgScore": 67.1,
          "weeklyDelta": 0.1,
          "top": [
            {
              "rank": 1,
              "company": "Chevron",
              "score": 78.6,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "ExxonMobil",
              "score": 77.1,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Shell",
              "score": 74.3,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "TotalEnergies",
              "score": 72.1,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Saudi Aramco",
              "score": 71,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Canacol Energy",
              "score": 38.2,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Occidental Petroleum",
              "score": 37.5,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "NRGL Energy",
              "score": 36.2,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "China Petroleum*",
              "score": 35.3,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Petronas Chemicals*",
              "score": 34.1,
              "delta": -0.3,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 7,
          "name": "Consumer & Retail",
          "avgScore": 64.9,
          "weeklyDelta": 0.2,
          "top": [
            {
              "rank": 1,
              "company": "Amazon",
              "score": 83.2,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Walmart",
              "score": 75.3,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Costco Wholesale",
              "score": 74.1,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "LVMH",
              "score": 71.2,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Nike",
              "score": 68.7,
              "delta": 0.2,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Cia. Hering",
              "score": 39.2,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Bed Bath & Beyond (Legacy)",
              "score": 37.4,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Big Lots",
              "score": 36.1,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Casino Guichard",
              "score": 34.8,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Sasa International",
              "score": 33.6,
              "delta": -0.2,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 8,
          "name": "Industrials",
          "avgScore": 66.8,
          "weeklyDelta": 0.3,
          "top": [
            {
              "rank": 1,
              "company": "Siemens",
              "score": 78.9,
              "delta": 0.5,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Honeywell",
              "score": 76.3,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Schneider Electric",
              "score": 74,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Caterpillar",
              "score": 72.3,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Deere & Company",
              "score": 69.1,
              "delta": 0.2,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "WeWork (Legacy)",
              "score": 37.9,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Katerra (Legacy)",
              "score": 36.1,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Enviva",
              "score": 35.4,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Cyient",
              "score": 34.2,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "PCX Aero",
              "score": 33,
              "delta": -0.2,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 9,
          "name": "Telecommunications",
          "avgScore": 62.3,
          "weeklyDelta": 0.2,
          "top": [
            {
              "rank": 1,
              "company": "AT&T",
              "score": 73.2,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Verizon",
              "score": 71.1,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "China Mobile",
              "score": 69.8,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Deutsche Telekom",
              "score": 68.7,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "America Movil",
              "score": 66.5,
              "delta": 0.2,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Altice Europe",
              "score": 37,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "VEON",
              "score": 35.8,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Bharat Airtel (Africa Ops)*",
              "score": 34.9,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Millicom",
              "score": 33.6,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Frontier Communications",
              "score": 32.4,
              "delta": -0.2,
              "trend": "down"
            }
          ]
        },
        {
          "rank": 10,
          "name": "Real Estate",
          "avgScore": 41.2,
          "weeklyDelta": -0.1,
          "top": [
            {
              "rank": 1,
              "company": "Prologis",
              "score": 59.3,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "American Tower",
              "score": 55.1,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Digital Realty",
              "score": 53.3,
              "delta": 0,
              "trend": "flat"
            },
            {
              "rank": 4,
              "company": "Simon Property Group",
              "score": 51.2,
              "delta": 0,
              "trend": "flat"
            },
            {
              "rank": 5,
              "company": "Equinix",
              "score": 50.4,
              "delta": 0,
              "trend": "flat"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Evergrande (Legacy)",
              "score": 17.6,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Country Garden (Legacy)",
              "score": 19.2,
              "delta": 0,
              "trend": "flat"
            },
            {
              "rank": 3,
              "company": "China Vanke (A-Shares)",
              "score": 20.1,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Signa (Legacy)",
              "score": 21.3,
              "delta": 0,
              "trend": "flat"
            },
            {
              "rank": 5,
              "company": "New World Development",
              "score": 22.4,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        }
      ],
      "industryLeadersByPillar": [
        {
          "pillar": "Innovation Velocity",
          "leader": "NVIDIA"
        },
        {
          "pillar": "Capital Efficiency",
          "leader": "JPMorgan Chase & Co."
        },
        {
          "pillar": "Productivity Acceleration",
          "leader": "Siemens"
        },
        {
          "pillar": "Infrastructure Leadership",
          "leader": "Amazon"
        },
        {
          "pillar": "Discovery Capacity",
          "leader": "Roche"
        }
      ]
    },
    "europe": {
      "weekEnding": "2026-07-25",
      "europeAverage": {
        "score": 72.8,
        "delta": 0.4
      },
      "highestCorporate": {
        "name": "ASML Holding",
        "country": "Netherlands",
        "score": 94.8
      },
      "lowestCorporate": {
        "name": "New World Development",
        "country": "Germany",
        "score": 18.7
      },
      "countries": [
        {
          "name": "Germany",
          "countryGVI": 82.8,
          "delta": 0.1,
          "trend": "up",
          "top": [
            {
              "rank": 1,
              "company": "SAP",
              "score": 90.1,
              "delta": 0.8,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Siemens",
              "score": 87.6,
              "delta": 0.5,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Allianz",
              "score": 83.5,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Deutsche Telekom",
              "score": 78.8,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "BASF",
              "score": 76.9,
              "delta": 0.2,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "New World Dev.",
              "score": 18.7,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Adler Group",
              "score": 21.3,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Euroboden",
              "score": 22.6,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "HelloFresh",
              "score": 24,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "VARTA AG",
              "score": 25.1,
              "delta": -0.2,
              "trend": "down"
            }
          ]
        },
        {
          "name": "France",
          "countryGVI": 81.4,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "LVMH",
              "score": 89,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "L'Oréal",
              "score": 85.2,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Schneider Electric",
              "score": 82.1,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Airbus",
              "score": 78.6,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "TotalEnergies",
              "score": 76.8,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Atos",
              "score": 19.5,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Casino Guichard",
              "score": 20.8,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Eurotunnel",
              "score": 22.4,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Orpea",
              "score": 22.9,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Camaieu",
              "score": 23.6,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        },
        {
          "name": "United Kingdom",
          "countryGVI": 82.1,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "Rolls-Royce",
              "score": 86.7,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "AstraZeneca",
              "score": 84.1,
              "delta": 0.5,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "HSBC Holdings",
              "score": 82.3,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Shell",
              "score": 79.1,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "RELX Group",
              "score": 76.3,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Cineworld Group",
              "score": 18.9,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Anglo Asian Mining",
              "score": 20.3,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "EasyJet",
              "score": 22.1,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Telegraph Media",
              "score": 22.5,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "TI Fluid Systems",
              "score": 23.4,
              "delta": -0.2,
              "trend": "down"
            }
          ]
        },
        {
          "name": "Netherlands",
          "countryGVI": 80.1,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "ASML Holding",
              "score": 94.8,
              "delta": 0.8,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "NXP Semiconductors",
              "score": 83.7,
              "delta": 0.5,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Prosus",
              "score": 78.5,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Ahold Delhaize",
              "score": 76.7,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "ING Group",
              "score": 75.1,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Basic-Fit",
              "score": 20.2,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Eurocommercial",
              "score": 21.5,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Fagron",
              "score": 22.7,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Sligro Food Group",
              "score": 23.3,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Signify NV",
              "score": 24,
              "delta": -0.2,
              "trend": "down"
            }
          ]
        },
        {
          "name": "Switzerland",
          "countryGVI": 80.7,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "Roche Holding",
              "score": 90.2,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Nestlé",
              "score": 84.8,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Novartis",
              "score": 82.7,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "ABB Ltd",
              "score": 78.4,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "UBS Group",
              "score": 76.9,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Comet Holding",
              "score": 20.7,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Meyer Burger",
              "score": 21.4,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Kuros (BioTech)",
              "score": 22.1,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Idorsia Ltd",
              "score": 22.9,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Addex Therapeutics",
              "score": 23.5,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        },
        {
          "name": "Sweden",
          "countryGVI": 78.9,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "Ericsson",
              "score": 82.1,
              "delta": 0.5,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Spotify Technology",
              "score": 78.3,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Volvo Group",
              "score": 76.9,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Atlas Copco",
              "score": 75.1,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Evolution AB",
              "score": 74.2,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Northvolt",
              "score": 18.9,
              "delta": -0.4,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "SBB (Publ)",
              "score": 20.6,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "NIBE Industrier",
              "score": 21.7,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Sinch AB",
              "score": 22.5,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Qliro Group",
              "score": 23.1,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        },
        {
          "name": "Denmark",
          "countryGVI": 77.8,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "Novo Nordisk",
              "score": 89.1,
              "delta": 0.6,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Maersk",
              "score": 81.2,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Vestas Wind Systems",
              "score": 76.8,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Carlsberg Group",
              "score": 75.3,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Genmab",
              "score": 74,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "DFDS",
              "score": 20,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Bavarian Nordic",
              "score": 20.7,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Zealand Pharma",
              "score": 21.6,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Orsted",
              "score": 22.9,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "FLSmidth",
              "score": 23.4,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        },
        {
          "name": "Norway",
          "countryGVI": 77.2,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "Equinor",
              "score": 86,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "DNB Bank",
              "score": 75.6,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Telenor",
              "score": 74.1,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Aker BP",
              "score": 72.6,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Yara International",
              "score": 71.3,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Nordic Leisure Travel",
              "score": 19.2,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Austevoll Seafood",
              "score": 20.1,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Elkem",
              "score": 21,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Q-free ASA",
              "score": 21.8,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Seadrill Limited",
              "score": 22.6,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        },
        {
          "name": "Spain",
          "countryGVI": 74.6,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "Inditex",
              "score": 79.8,
              "delta": 0.4,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Iberdrola",
              "score": 76.8,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Banco Santander",
              "score": 74.5,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Cellnex Telecom",
              "score": 71.8,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Amadeus IT Group",
              "score": 70.3,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Grifols",
              "score": 20.4,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "CIE Automotive",
              "score": 21.4,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Audax Renovables",
              "score": 22.5,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Duro Felguera",
              "score": 23.2,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Ezentis",
              "score": 23.9,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        },
        {
          "name": "Italy",
          "countryGVI": 71.8,
          "delta": 0,
          "trend": "flat",
          "top": [
            {
              "rank": 1,
              "company": "Enel",
              "score": 75.2,
              "delta": 0.3,
              "trend": "up"
            },
            {
              "rank": 2,
              "company": "Eni",
              "score": 73.4,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 3,
              "company": "Intesa Sanpaolo",
              "score": 72,
              "delta": 0.2,
              "trend": "up"
            },
            {
              "rank": 4,
              "company": "Ferrari",
              "score": 71.1,
              "delta": 0.1,
              "trend": "up"
            },
            {
              "rank": 5,
              "company": "Leonardo",
              "score": 69.3,
              "delta": 0.1,
              "trend": "up"
            }
          ],
          "bottom": [
            {
              "rank": 1,
              "company": "Banca Monte dei Paschi",
              "score": 18.9,
              "delta": -0.3,
              "trend": "down"
            },
            {
              "rank": 2,
              "company": "Unieuro",
              "score": 20.3,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 3,
              "company": "Cerved Group",
              "score": 21.2,
              "delta": -0.2,
              "trend": "down"
            },
            {
              "rank": 4,
              "company": "Danieli & C. Officine",
              "score": 22.3,
              "delta": -0.1,
              "trend": "down"
            },
            {
              "rank": 5,
              "company": "Geox",
              "score": 22.9,
              "delta": -0.1,
              "trend": "down"
            }
          ]
        }
      ],
      "pillarLeaders": [
        {
          "pillar": "Intelligence Infrastructure",
          "leader": "ASML Holding"
        },
        {
          "pillar": "Innovation Velocity",
          "leader": "Roche Holding"
        },
        {
          "pillar": "Enterprise Transformation",
          "leader": "SAP"
        },
        {
          "pillar": "Smart Capital",
          "leader": "HSBC Holdings"
        },
        {
          "pillar": "Productivity Acceleration",
          "leader": "Siemens"
        },
        {
          "pillar": "Discovery Capacity",
          "leader": "AstraZeneca"
        }
      ]
    },
    "banks": {
      "weekEnding": "2026-07-25",
      "europeanBanksAverage": {
        "score": 72.4,
        "delta": 0.5
      },
      "highestBank": {
        "name": "ING Group",
        "country": "Netherlands",
        "score": 90.2
      },
      "lowestBank": {
        "name": "Banca MPS",
        "country": "Italy",
        "score": 38.6
      },
      "topOverall": [
        {
          "rank": 1,
          "bank": "ING Group",
          "country": "Netherlands",
          "score": 90.2,
          "delta": 0.8,
          "trend": "up"
        },
        {
          "rank": 2,
          "bank": "Nordea Bank",
          "country": "Sweden",
          "score": 87.6,
          "delta": 0.6,
          "trend": "up"
        },
        {
          "rank": 3,
          "bank": "BBVA",
          "country": "Spain",
          "score": 85.1,
          "delta": 0.6,
          "trend": "up"
        },
        {
          "rank": 4,
          "bank": "Danske Bank",
          "country": "Denmark",
          "score": 83,
          "delta": 0.4,
          "trend": "up"
        },
        {
          "rank": 5,
          "bank": "UBS Group",
          "country": "Switzerland",
          "score": 82.7,
          "delta": 0.3,
          "trend": "up"
        }
      ],
      "bottomOverall": [
        {
          "rank": 106,
          "bank": "Banca Monte dei Paschi di Siena",
          "country": "Italy",
          "score": 38.6,
          "delta": -0.4,
          "trend": "down"
        },
        {
          "rank": 107,
          "bank": "BPER Banca",
          "country": "Italy",
          "score": 40.5,
          "delta": -0.3,
          "trend": "down"
        },
        {
          "rank": 108,
          "bank": "Erste Group Bank",
          "country": "Austria",
          "score": 42.1,
          "delta": -0.2,
          "trend": "down"
        },
        {
          "rank": 109,
          "bank": "Alpha Bank",
          "country": "Greece",
          "score": 43.7,
          "delta": -0.2,
          "trend": "down"
        },
        {
          "rank": 110,
          "bank": "Banco Popolare di Sondrio",
          "country": "Italy",
          "score": 45.3,
          "delta": -0.2,
          "trend": "down"
        }
      ],
      "pillarWeighting": [
        {
          "pillar": "Intelligence Infrastructure",
          "weight": "25%"
        },
        {
          "pillar": "Innovation Velocity",
          "weight": "20%"
        },
        {
          "pillar": "Enterprise Transformation",
          "weight": "20%"
        },
        {
          "pillar": "Smart Capital",
          "weight": "20%"
        },
        {
          "pillar": "Discovery Capacity",
          "weight": "15%"
        }
      ],
      "countries": [
        {
          "name": "Germany",
          "countryAvgGVI": 72.7,
          "top": [
            {
              "rank": 1,
              "bank": "Deutsche Bank",
              "score": 78.8
            },
            {
              "rank": 2,
              "bank": "Commerzbank",
              "score": 72.1
            },
            {
              "rank": 3,
              "bank": "DZ Bank",
              "score": 69.1
            },
            {
              "rank": 4,
              "bank": "HypoVereinsbank",
              "score": 68.4
            },
            {
              "rank": 5,
              "bank": "UniCredit (Germany)",
              "score": 67.3
            }
          ]
        },
        {
          "name": "France",
          "countryAvgGVI": 71.8,
          "top": [
            {
              "rank": 1,
              "bank": "BNP Paribas",
              "score": 82.6
            },
            {
              "rank": 2,
              "bank": "Crédit Agricole S.A.",
              "score": 77
            },
            {
              "rank": 3,
              "bank": "Société Générale",
              "score": 67.9
            },
            {
              "rank": 4,
              "bank": "BPCE Group",
              "score": 66.3
            },
            {
              "rank": 5,
              "bank": "Crédit Mutuel",
              "score": 64.9
            }
          ]
        },
        {
          "name": "United Kingdom",
          "countryAvgGVI": 72.4,
          "top": [
            {
              "rank": 1,
              "bank": "HSBC Holdings",
              "score": 80.1
            },
            {
              "rank": 2,
              "bank": "Barclays",
              "score": 75
            },
            {
              "rank": 3,
              "bank": "Lloyds Banking Group",
              "score": 72.4
            },
            {
              "rank": 4,
              "bank": "NatWest Group",
              "score": 69.5
            },
            {
              "rank": 5,
              "bank": "Standard Chartered UK",
              "score": 68.4
            }
          ]
        },
        {
          "name": "Netherlands",
          "countryAvgGVI": 76,
          "top": [
            {
              "rank": 1,
              "bank": "ING Group",
              "score": 90.2
            },
            {
              "rank": 2,
              "bank": "Rabobank",
              "score": 73.8
            },
            {
              "rank": 3,
              "bank": "ABN AMRO",
              "score": 72.6
            },
            {
              "rank": 4,
              "bank": "Van Lanschot Kempen",
              "score": 66.9
            },
            {
              "rank": 5,
              "bank": "ASN Bank",
              "score": 64.1
            }
          ]
        },
        {
          "name": "Switzerland",
          "countryAvgGVI": 75.9,
          "top": [
            {
              "rank": 1,
              "bank": "UBS Group",
              "score": 82.7
            },
            {
              "rank": 2,
              "bank": "Credit Suisse (UBS)",
              "score": 79.1
            },
            {
              "rank": 3,
              "bank": "Zürcher Kantonalbank",
              "score": 74.4
            },
            {
              "rank": 4,
              "bank": "Julius Baer",
              "score": 71.2
            },
            {
              "rank": 5,
              "bank": "Pictet & Cie",
              "score": 67.8
            }
          ]
        },
        {
          "name": "Sweden",
          "countryAvgGVI": 73.6,
          "top": [
            {
              "rank": 1,
              "bank": "Nordea Bank",
              "score": 87.6
            },
            {
              "rank": 2,
              "bank": "SEB",
              "score": 73.6
            },
            {
              "rank": 3,
              "bank": "Swedbank",
              "score": 69.5
            },
            {
              "rank": 4,
              "bank": "Handelsbanken",
              "score": 68.3
            },
            {
              "rank": 5,
              "bank": "Skandinaviska Enskilda",
              "score": 64
            }
          ]
        },
        {
          "name": "Denmark",
          "countryAvgGVI": 73.3,
          "top": [
            {
              "rank": 1,
              "bank": "Danske Bank",
              "score": 83
            },
            {
              "rank": 2,
              "bank": "Jyske Bank",
              "score": 67.3
            },
            {
              "rank": 3,
              "bank": "Nykredit",
              "score": 64.2
            },
            {
              "rank": 4,
              "bank": "Sydbank",
              "score": 61.1
            },
            {
              "rank": 5,
              "bank": "Arbejdernes Landsbank",
              "score": 59.3
            }
          ]
        },
        {
          "name": "Spain",
          "countryAvgGVI": 74.6,
          "top": [
            {
              "rank": 1,
              "bank": "BBVA",
              "score": 85.1
            },
            {
              "rank": 2,
              "bank": "Banco Santander",
              "score": 82.4
            },
            {
              "rank": 3,
              "bank": "CaixaBank",
              "score": 78.1
            },
            {
              "rank": 4,
              "bank": "Bankinter",
              "score": 70.4
            },
            {
              "rank": 5,
              "bank": "Sabadell Bank",
              "score": 66.6
            }
          ]
        },
        {
          "name": "Italy",
          "countryAvgGVI": 63.4,
          "top": [
            {
              "rank": 1,
              "bank": "Intesa Sanpaolo",
              "score": 72
            },
            {
              "rank": 2,
              "bank": "UniCredit",
              "score": 68.6
            },
            {
              "rank": 3,
              "bank": "BPER Banca",
              "score": 57.1
            },
            {
              "rank": 4,
              "bank": "Banco BPM",
              "score": 55.8
            },
            {
              "rank": 5,
              "bank": "Credem Banca",
              "score": 52.9
            }
          ]
        }
      ]
    }
  },
  "today": {
    "date": "2026-09-14",
    "edition": "The Morning View",
    "thesis": "The Three Speed Limits",
    "subtitle": "Energy. Capital. Governance.",
    "standfirst": "Velocity is no longer speed alone. It is speed that survives its constraints.",
    "velocityReading": {
      "score": 98,
      "max": 100,
      "label": "The Three Speed Limits",
      "trend": "up"
    },
    "strip": [
      {
        "label": "Brent",
        "value": "$107.36",
        "delta": "+1.8%",
        "trend": "up"
      },
      {
        "label": "US 10Y",
        "value": "4.97%",
        "delta": "+0.06",
        "trend": "up"
      },
      {
        "label": "Fed hike prob.",
        "value": "86%",
        "trend": "flat"
      },
      {
        "label": "Nasdaq futures",
        "value": "-1.1%",
        "trend": "down"
      },
      {
        "label": "S. Korea equities",
        "value": "-2.1%",
        "trend": "down"
      }
    ]
  },
  "market": {
    "asOf": "2026-09-14",
    "title": "Key Numbers to Watch",
    "rows": [
      {
        "k": "Brent",
        "v": "~$107.8/bbl",
        "note": "Energy premium remains elevated",
        "trend": "up"
      },
      {
        "k": "WTI",
        "v": "~$102.9/bbl",
        "note": "U.S. inflation transmission",
        "trend": "up"
      },
      {
        "k": "US 10Y Treasury",
        "v": "~4.97%",
        "note": "The 5% wall",
        "trend": "up"
      },
      {
        "k": "Fed hike probability",
        "v": "~86%",
        "note": "September hike base case",
        "trend": "up"
      },
      {
        "k": "BOJ hike probability",
        "v": "~76%",
        "note": "Global tightening broadens",
        "trend": "up"
      },
      {
        "k": "USD/JPY",
        "v": "~153.98",
        "note": "Yen stabilization vs. tightening",
        "trend": "flat"
      },
      {
        "k": "EUR/USD",
        "v": "~1.1565",
        "note": "Europe-dollar yield differential",
        "trend": "flat"
      },
      {
        "k": "Gold",
        "v": "~$4,329/oz",
        "note": "High real yields, geopolitical bid",
        "trend": "up"
      },
      {
        "k": "Nasdaq futures",
        "v": "~-1.3%",
        "note": "AI-duration repricing",
        "trend": "down"
      },
      {
        "k": "S&P 500 futures",
        "v": "~-0.5%",
        "note": "Broader risk-off",
        "trend": "down"
      },
      {
        "k": "EURO STOXX 50 futures",
        "v": "~-0.4%",
        "note": "Europe opens defensively",
        "trend": "down"
      },
      {
        "k": "Nikkei",
        "v": "~-1.0%",
        "note": "AI and rates pressure",
        "trend": "down"
      },
      {
        "k": "KOSPI",
        "v": "~-3.2%",
        "note": "Semiconductor selloff",
        "trend": "down"
      },
      {
        "k": "Hormuz commodity transits",
        "v": "Single digits/day",
        "note": "Severe shipping disruption",
        "trend": "down"
      },
      {
        "k": "Saudi East-West pipeline",
        "v": "4-5 mb/d",
        "note": "Principal bypass route impaired",
        "trend": "down"
      },
      {
        "k": "KEPCO power prepayment",
        "v": "$18.7B",
        "note": "Who finances semiconductor power?",
        "trend": "flat"
      },
      {
        "k": "Z.AI capital raise",
        "v": "$5B",
        "note": "China AI capital formation",
        "trend": "up"
      }
    ]
  },
  "velocity": {
    "asOf": "2026-09-14",
    "overall": {
      "score": 98,
      "max": 100,
      "label": "Morning Velocity Reading"
    },
    "scale": "0 = constrained · 100 = unconstrained",
    "rows": [
      {
        "name": "AI Infrastructure Demand",
        "score": 100,
        "arrows": 4,
        "trend": "up"
      },
      {
        "name": "Energy Scarcity",
        "score": 97,
        "arrows": 4,
        "trend": "up"
      },
      {
        "name": "Global Cost of Capital",
        "score": 90,
        "arrows": 4,
        "trend": "up"
      },
      {
        "name": "AI Governance Risk",
        "score": 92,
        "arrows": 4,
        "trend": "up"
      },
      {
        "name": "Geopolitical Risk",
        "score": 96,
        "arrows": 4,
        "trend": "up"
      },
      {
        "name": "Sovereign Capital",
        "score": 88,
        "arrows": 4,
        "trend": "up"
      },
      {
        "name": "Europe Opportunity",
        "score": 91,
        "arrows": 4,
        "trend": "up"
      },
      {
        "name": "Resilience Premium",
        "score": 100,
        "arrows": 4,
        "trend": "up"
      }
    ]
  },
  "corporateBenchmark": {
    "asOf": "2026-09-14",
    "title": "GVI Corporate Benchmark",
    "leaders": [
      {
        "rank": 1,
        "name": "TSMC",
        "score": 99.6,
        "delta": 0,
        "trend": "up",
        "note": "Frontier manufacturing and advanced packaging"
      },
      {
        "rank": 2,
        "name": "Microsoft",
        "score": 99.3,
        "delta": 0,
        "trend": "up",
        "note": "Azure, enterprise distribution and proprietary silicon"
      },
      {
        "rank": 3,
        "name": "Amazon",
        "score": 99.2,
        "delta": 0,
        "trend": "up",
        "note": "AWS and global AI distribution"
      },
      {
        "rank": 4,
        "name": "Schneider Electric",
        "score": 98.4,
        "delta": 0.1,
        "trend": "up",
        "note": "Electrical infrastructure and energy management"
      },
      {
        "rank": 5,
        "name": "Nvidia",
        "score": 98,
        "delta": -0.1,
        "trend": "down",
        "note": "Accelerated-computing ecosystem"
      },
      {
        "rank": 6,
        "name": "Broadcom",
        "score": 97.8,
        "delta": 0,
        "trend": "up",
        "note": "Custom accelerators and networking"
      },
      {
        "rank": 7,
        "name": "Palantir",
        "score": 97.4,
        "delta": 0,
        "trend": "up",
        "note": "Operational AI and capital-light conversion"
      },
      {
        "rank": 8,
        "name": "Siemens AG",
        "score": 97.2,
        "delta": 0,
        "trend": "up",
        "note": "Industrial AI and automation"
      },
      {
        "rank": 9,
        "name": "Siemens Energy",
        "score": 97.2,
        "delta": 0.2,
        "trend": "up",
        "note": "Turbines, grids and the electricity bottleneck"
      },
      {
        "rank": 10,
        "name": "Cisco",
        "score": 97,
        "delta": 0,
        "trend": "up",
        "note": "AI networking and system-throughput architecture"
      }
    ],
    "laggards": [
      {
        "rank": 1,
        "name": "Volkswagen",
        "score": 62.3,
        "delta": -0.1,
        "trend": "down",
        "note": "Overcapacity and China erosion"
      },
      {
        "rank": 2,
        "name": "Nissan",
        "score": 63.6,
        "delta": -0.1,
        "trend": "down",
        "note": "Scale disadvantage"
      },
      {
        "rank": 3,
        "name": "Stellantis",
        "score": 64.8,
        "delta": -0.1,
        "trend": "down",
        "note": "Product gaps and EV write-downs"
      },
      {
        "rank": 4,
        "name": "Warner Bros. Discovery",
        "score": 67.2,
        "delta": 0,
        "trend": "flat",
        "note": "Legacy-media economics"
      },
      {
        "rank": 5,
        "name": "Adidas",
        "score": 68.1,
        "delta": 0,
        "trend": "flat",
        "note": "Insufficient operating conversion"
      },
      {
        "rank": 6,
        "name": "BASF",
        "score": 69.4,
        "delta": -0.3,
        "trend": "down",
        "note": "European energy disadvantage"
      },
      {
        "rank": 7,
        "name": "Honda",
        "score": 70,
        "delta": -0.2,
        "trend": "down",
        "note": "EV transition costs"
      },
      {
        "rank": 8,
        "name": "Prudential",
        "score": 70.3,
        "delta": 0,
        "trend": "flat",
        "note": "Regulatory exposure in China"
      },
      {
        "rank": 9,
        "name": "Porsche",
        "score": 71.2,
        "delta": -0.2,
        "trend": "down",
        "note": "China weakness"
      },
      {
        "rank": 10,
        "name": "Cellnex",
        "score": 71.8,
        "delta": 0,
        "trend": "flat",
        "note": "Infrastructure scale without productivity acceleration"
      }
    ],
    "pillars": [
      {
        "pillar": "Innovation Velocity",
        "leaders": [
          "TSMC",
          "Nvidia",
          "Palantir"
        ]
      },
      {
        "pillar": "Capital Formation",
        "leaders": [
          "Microsoft",
          "Amazon",
          "TSMC"
        ]
      },
      {
        "pillar": "Productivity Acceleration",
        "leaders": [
          "Palantir",
          "Siemens",
          "Microsoft"
        ]
      },
      {
        "pillar": "AI Adoption & Deployment",
        "leaders": [
          "Microsoft",
          "Palantir",
          "Siemens"
        ]
      },
      {
        "pillar": "Infrastructure Position",
        "leaders": [
          "Schneider",
          "Siemens Energy"
        ]
      },
      {
        "pillar": "Ecosystem Strength",
        "leaders": [
          "Microsoft",
          "Nvidia",
          "Amazon"
        ]
      },
      {
        "pillar": "Resilience",
        "leaders": [
          "TSMC",
          "Schneider",
          "Microsoft"
        ]
      },
      {
        "pillar": "Talent Intensity",
        "leaders": [
          "Nvidia",
          "TSMC",
          "Microsoft"
        ]
      },
      {
        "pillar": "Strategic Optionality",
        "leaders": [
          "Microsoft",
          "Amazon",
          "TSMC"
        ]
      },
      {
        "pillar": "Execution Quality",
        "leaders": [
          "TSMC",
          "Schneider",
          "Siemens"
        ]
      }
    ]
  },
  "indices": {
    "espresso": {
      "asOf": "2026-09-05",
      "title": "The Espresso Index",
      "subtitle": "Industrial Intelligence Purchasing Power",
      "constant": "€2 = $2.3228",
      "rows": [
        {
          "rank": 1,
          "flag": "🇺🇸",
          "name": "United States",
          "score": 100,
          "note": "Deepest AI stack + capital + hyperscale capacity"
        },
        {
          "rank": 2,
          "flag": "🇰🇷",
          "name": "South Korea",
          "score": 98.2,
          "note": "AI exports now feeding profits, taxes and reinvestment"
        },
        {
          "rank": 3,
          "flag": "🇨🇳",
          "name": "China",
          "score": 96.4,
          "note": "Scale + lower-cost models + domestic hardware stack"
        },
        {
          "rank": 4,
          "flag": "🇹🇼",
          "name": "Taiwan",
          "score": 94.1,
          "note": "Extraordinary semiconductor leverage"
        },
        {
          "rank": 5,
          "flag": "🇸🇪",
          "name": "Sweden",
          "score": 91.7,
          "note": "Cheap electrons + strong grids + European AI geography"
        },
        {
          "rank": 6,
          "flag": "🇫🇮",
          "name": "Finland",
          "score": 90.9,
          "note": "Power advantage + EuroHPC/LUMI-AI capacity"
        },
        {
          "rank": 7,
          "flag": "🇳🇴",
          "name": "Norway",
          "score": 89.8,
          "note": "Exceptional energy economics, growing AI optionality"
        },
        {
          "rank": 8,
          "flag": "🇯🇵",
          "name": "Japan",
          "score": 89.2,
          "note": "Capital depth + expanding data-centre real assets"
        },
        {
          "rank": 9,
          "flag": "🇸🇬",
          "name": "Singapore",
          "score": 87.6,
          "note": "Capital and cloud density offset by power constraints"
        },
        {
          "rank": 10,
          "flag": "🇪🇸",
          "name": "Spain",
          "score": 85.7,
          "note": "Emerging European advantage in land + renewable power"
        },
        {
          "rank": 11,
          "flag": "🇫🇷",
          "name": "France",
          "score": 83.8,
          "note": "Nuclear power + sovereign AI infrastructure"
        },
        {
          "rank": 12,
          "flag": "🇳🇱",
          "name": "Netherlands",
          "score": 81.9,
          "note": "Dense digital ecosystem, constrained by powered-land costs"
        },
        {
          "rank": 13,
          "flag": "🇩🇪",
          "name": "Germany",
          "score": 79.3,
          "note": "Industrial absorption high; energy and capital cost penalize"
        },
        {
          "rank": 14,
          "flag": "🇮🇹",
          "name": "Italy",
          "score": 75.6,
          "note": "Industrial opportunity strong; infrastructure scaling gap"
        },
        {
          "rank": 15,
          "flag": "🇬🇧",
          "name": "United Kingdom",
          "score": 74.9,
          "note": "Deep capital markets but high power and land costs"
        }
      ],
      "velocity": [
        {
          "name": "Raw Intelligence Deflation",
          "score": 100
        },
        {
          "name": "Model Price Competition",
          "score": 100
        },
        {
          "name": "Inference Accessibility",
          "score": 100
        },
        {
          "name": "Accelerated-Computing Availability",
          "score": 82
        },
        {
          "name": "Memory Availability",
          "score": 69
        },
        {
          "name": "Power Availability",
          "score": 61
        },
        {
          "name": "Grid Velocity",
          "score": 48
        },
        {
          "name": "Capital Availability",
          "score": 83
        },
        {
          "name": "Industrial AI Absorption",
          "score": 77
        },
        {
          "name": "Global Espresso Velocity",
          "score": 86,
          "highlight": true
        },
        {
          "name": "Great Split Intensity",
          "score": 100,
          "highlight": true
        }
      ]
    }
  },
  "nextEconomy": {
    "asOf": "2026-09-14",
    "title": "Next Economy Dashboard",
    "hypothesis": "NERC Hypothesis 05 — The AI Absorption Multiplier",
    "rows": [
      {
        "k": "AI-linked equities",
        "latest": "SoftBank -13.2%, Kioxia -9.8%",
        "trend": "down",
        "reading": "Assurance risk priced"
      },
      {
        "k": "Frontier AI pacing",
        "latest": "CEOs support slower growth",
        "trend": "up",
        "reading": "Deployment split"
      },
      {
        "k": "Anthropic economics",
        "latest": "Op. profit (2nd qtr), >80% margins",
        "trend": "up",
        "reading": "Strong fundamentals"
      },
      {
        "k": "Industrial AI",
        "latest": "IMTS 2026, Physical AI demos",
        "trend": "up",
        "reading": "Integration accelerating"
      },
      {
        "k": "US data-centre pipeline",
        "latest": "~158 GW",
        "trend": "up",
        "reading": "Execution challenge"
      },
      {
        "k": "Europe data-centre pipeline",
        "latest": "~66 GW",
        "trend": "up",
        "reading": "Grid and labor constraint"
      },
      {
        "k": "Hyperscaler investment",
        "latest": "~3% U.S. GDP (2027-29 est.)",
        "trend": "up",
        "reading": "Macro-scale capital shock"
      },
      {
        "k": "Korea power financing",
        "latest": "$18.7B prepayment rejected",
        "trend": "down",
        "reading": "Contested financing"
      },
      {
        "k": "Construction labor (US)",
        "latest": "~439,000 workers short",
        "trend": "down",
        "reading": "Complementary scarcity"
      },
      {
        "k": "China HBM constraint",
        "latest": "No verified easing today",
        "trend": "flat",
        "reading": "Baseline unchanged"
      },
      {
        "k": "EU public-sector AI",
        "latest": "Three GenAI pilots launched",
        "trend": "up",
        "reading": "Policy to market"
      }
    ]
  }
};
