/* ============================================================
   THE VELOCITY EDGE — JOURNAL ENTRIES (single source of truth)
   To post a new entry: create its article HTML page, then add a
   new object to the TOP of this array (newest first). The home
   teaser cards and the journal (featured + grid + count) update
   automatically — no other edits needed.
   ============================================================ */
window.FDK_POSTS = [
  {
    url: "/the-next-economy-research-center-the-big-take",
    title: "The Next Economy Research Center: The Big Take",
    excerpt: "The Trump–Xi summit reframed rivalry as managed interdependence, raising structural capex while lowering extreme tail risk.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1642790551116-18e150f248e3?auto=format&fit=crop&w=800&q=80",
    date: "September 26, 2026",
    read: "3 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-ai-exception",
    title: "The AI Exception",
    excerpt: "Five numbers define a regime of Selective Acceleration, where the decisive question is who can turn AI capex into free cash flow fast enough to outrun the hurdle rate.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
    date: "September 26, 2026",
    read: "3 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-capital-efficiency-test",
    title: "The Capital Efficiency Test",
    excerpt: "With the U.S. 10-year Treasury at 5.158%, capital discipline is now the dividing line between AI growth and AI value creation.",
    tag: "FDK GVI Corporate Benchmark · Capital",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1444927714506-8492d94b4e3d?auto=format&fit=crop&w=800&q=80",
    date: "September 26, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/financial-verdict",
    title: "Financial Verdict",
    excerpt: "The next re-rating will separate AI cash generators from AI capital consumers.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=800&q=80",
    date: "September 26, 2026",
    read: "2 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-price-of-proof",
    title: "The Price of Proof",
    excerpt: "The AI Supercycle has reached the underwriting desk — capital is moving toward bankable AI.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80",
    date: "September 25, 2026",
    read: "2 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/the-intelligence-power-race",
    title: "The Intelligence Power Race",
    excerpt: "The AI race is no longer about models or chips—it is about the system that turns intelligence into capital, and Europe has a deadline.",
    tag: "Europe AI Gigafactory Watch · Capital",
    slot: "Europe AI Gigafactory Watch",
    image: "https://images.unsplash.com/photo-1454372182658-c712e4c5a1db?auto=format&fit=crop&w=800&q=80",
    date: "September 25, 2026",
    read: "2 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/ai-is-moving-from-productivity-story-to-cost-of-capital-story",
    title: "AI Is Moving From Productivity Story to Cost-of-capital Story",
    excerpt: "The ECB, BoE and SNB reveal a Great Split in how the AI shock transmits into yields, inflation and policy.",
    tag: "Central Banks & AI Watch · Macro",
    slot: "Central Banks & AI Watch",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    date: "September 25, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/compete-harder-escalate-less-invest-more",
    title: "Compete Harder. Escalate Less. Invest More.",
    excerpt: "Washington and Beijing postponed their deepest disputes — creating the strategic stability that could extend two rival AI capital cycles.",
    tag: "U.s. · Geopolitics",
    slot: "U.s.",
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80",
    date: "September 25, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/resolved-i-standardized-every-reference-to-the-same-benchmark-the-u-s-10-year-treasury-yield-at-approximately-5-2",
    title: "Resolved. I Standardized Every Reference to the Same Benchmark: The U.S. 10-year Treasury Yield at Approximately 5.2%.",
    excerpt: "The FDK GVI Corporate Benchmark on why powered, commissioned capacity — not contracts — is the new premium.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=80",
    date: "September 25, 2026",
    read: "5 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/5-avoid-stranded-scale",
    title: "5: Avoid: Stranded Scale",
    excerpt: "With U.S. long yields at multi-decade highs, AI growth must now compete for capital on materially tougher terms.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1500673922987-e212871fec22?auto=format&fit=crop&w=800&q=80",
    date: "September 25, 2026",
    read: "3 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/europe-back-to-the-table",
    title: "Europe: Back to the Table",
    excerpt: "A managed bipolar system is forming; Europe must invest its way back to the negotiating table.",
    tag: "In Focus · Geopolitics",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/dopo-trump-xi-la-corsa-accelera",
    title: "Dopo Trump: Xi, La Corsa Accelera",
    excerpt: "Una relazione USA–Cina più prevedibile non riduce l'urgenza europea sull'AI: la aumenta.",
    tag: "The Velocity Edge · Europe AI Gigafactory Watch · AI",
    slot: "The Velocity Edge · Europe AI Gigafactory Watch",
    image: "https://images.unsplash.com/photo-1504198266287-1659872e6590?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/europes-ai-deadline",
    title: "Europe’s AI Deadline",
    excerpt: "A more predictable U.S.–China relationship could accelerate AI compounding — and make Europe's position harder, not easier.",
    tag: "Europe AI Gigafactory Watch · Capital",
    slot: "Europe AI Gigafactory Watch",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "5 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-855-billion-capacity-divide",
    title: "The $855 Billion Capacity Divide",
    excerpt: "Amazon added roughly $379 billion in value while Apple erased about $477 billion. The divergence exposed a new law of the AI economy — the market now pays for deliverable capacity, not the promise of intelligence.",
    tag: "Midday Pulse · Capital · Three-Part Edition",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80",
    date: "August 6, 2026",
    read: "12 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/ai-is-growing-jobs-are-not",
    title: "AI Is Growing. Jobs Are Not.",
    excerpt: "US services are expanding and profits remain strong, yet hiring is slowing. AI is becoming deflationary for labor while remaining inflationary for capital and infrastructure.",
    tag: "Midday Pulse · The Great Split",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80",
    date: "August 6, 2026",
    read: "2 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-big-take",
    title: "The Big Take",
    excerpt: "The Trump–Xi summit signals a shift from unmanaged rivalry to a managed architecture of strategic competition.",
    tag: "U.s. · Geopolitics",
    slot: "U.s.",
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "5 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-cost-of-control",
    title: "The Cost of Control",
    excerpt: "With five-year Treasuries above 5%, the competitive test moves from AI capability to economic capture.",
    tag: "Quick Take · Capital",
    slot: "Quick Take",
    image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "5 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-private-capital-vote",
    title: "The Private-capital Vote",
    excerpt: "The Treasury's abstention converts the MPS defensive vote from government versus market into private capital versus private capital.",
    tag: "In Focus · Banking",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-cost-of-acceleration",
    title: "The Cost of Acceleration",
    excerpt: "Five numbers frame a market where AI velocity collides with the rising cost of capital, energy and infrastructure.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/gvi-corporate-benchmark-quick-take",
    title: "GVI Corporate Benchmark: Quick Take",
    excerpt: "The winners will not simply build the most capable AI — they will control the boundary between intelligence and action.",
    tag: "Add This Just Before the Velocity Edge Section · Capital",
    slot: "Add This Just Before the Velocity Edge Section",
    image: "https://images.unsplash.com/photo-1642790551116-18e150f248e3?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/provisional-nowcast",
    title: "Provisional Nowcast",
    excerpt: "AI is now visible on both sides of the macro equation — supporting growth while keeping capital expensive.",
    tag: "FDK Global Velocity Index · Macro",
    slot: "FDK Global Velocity Index",
    image: "https://images.unsplash.com/photo-1444927714506-8492d94b4e3d?auto=format&fit=crop&w=800&q=80",
    date: "September 24, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-capacity-wall",
    title: "The Capacity Wall",
    excerpt: "American business activity hit a five-year high, the 10-year broke above 5%, yet capital kept pouring into the AI build-out.",
    tag: "The Close · Macro",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=800&q=80",
    date: "September 23, 2026",
    read: "9 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/the-disclosure-test",
    title: "The Disclosure Test",
    excerpt: "Consob, not another bidder, is now setting the pace of the Italian Banking Risiko.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80",
    date: "September 23, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-architecture-of-the-new-bank",
    title: "The Architecture of the New Bank",
    excerpt: "MPS's defence hardens into an industrial plan as Brussels turns pro-scale and Generali moves to the centre of gravity.",
    tag: "The Italian Banking Tipping Point · Capital",
    slot: "The Italian Banking Tipping Point",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/global-cities-ranking",
    title: "Global Cities Ranking",
    excerpt: "Communities are starting to demand a direct economic return for surrendering electricity, water, land and infrastructure to AI.",
    tag: "GVI Global Cities Signature Survey · Urban Velocity",
    slot: "GVI Global Cities Signature Survey",
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-great-bifurcation",
    title: "The Great Bifurcation",
    excerpt: "AI has become a macroeconomic variable, and central banks now face its demand shock years before its productivity dividend arrives.",
    tag: "Central Banks & AI Watch · Macro",
    slot: "Central Banks & AI Watch",
    image: "https://images.unsplash.com/photo-1454372182658-c712e4c5a1db?auto=format&fit=crop&w=800&q=80",
    date: "September 22, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-hurdle-rate",
    title: "The Hurdle Rate",
    excerpt: "When oil and yields eased together, capital rushed straight back into semiconductors — revealing the true constraint on the AI Supercycle.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1500673922987-e212871fec22?auto=format&fit=crop&w=800&q=80",
    date: "September 21, 2026",
    read: "5 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/financeable-powered-intelligence",
    title: "Financeable Powered Intelligence",
    excerpt: "As AI infrastructure becomes a credit asset, power delays, permitting and offtake now flow straight into spreads and WACC.",
    tag: "Europe AI Gigafactory Watch · Capital",
    slot: "Europe AI Gigafactory Watch",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-denominator",
    title: "The Denominator",
    excerpt: "Central banks converge on tightening as the AI Supercycle turns physical — and the dividing line becomes productive capital versus capital that arrives too late.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?auto=format&fit=crop&w=800&q=80",
    date: "September 18, 2026",
    read: "5 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/the-bottleneck-is-the-asset",
    title: "The Bottleneck Is the Asset",
    excerpt: "Capital is becoming more expensive, energy more strategic and intelligence cheaper — and value migrates to whoever can connect the three.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=800&q=80",
    date: "September 16, 2026",
    read: "5 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/the-deployability-premium",
    title: "The Deployability Premium",
    excerpt: "The Next Economy crosses another threshold as the market rewards deployability over raw capability.",
    tag: "FDK GVI Corporate Benchmark · Capital",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    date: "September 23, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-alliance-option",
    title: "The Alliance Option",
    excerpt: "A reported UniCredit–Crédit Agricole dialogue over Banco BPM signals a shift from consolidation to coalition-building.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1500673922987-e212871fec22?auto=format&fit=crop&w=800&q=80",
    date: "September 22, 2026",
    read: "6 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-compounding-stack",
    title: "The Compounding Stack",
    excerpt: "Alibaba builds a self-reinforcing AI stack, AMD crosses $1 trillion as a systems company, and the Next Economy enters its compounding phase.",
    tag: "FDK GVI Corporate Benchmark · Capital",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80",
    date: "September 22, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/global-velocity-index-country-rankings",
    title: "Global Velocity Index: Country Rankings",
    excerpt: "The Global Velocity Index ranks which economies convert AI, capital, energy and industry into acceleration fastest.",
    tag: "The Close · Macro",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    date: "September 20, 2026",
    read: "5 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/material-inflection-detected",
    title: "Material Inflection Detected",
    excerpt: "China's central bank warns AI may deepen excess supply rather than stoke inflation, splitting the world into distinct monetary regimes.",
    tag: "Central Banks & AI Watch · Macro",
    slot: "Central Banks & AI Watch",
    image: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=800&q=80",
    date: "September 20, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-governance-premium",
    title: "The Governance Premium",
    excerpt: "Weekend reporting reveals the governance architecture behind the MPS defence, shifting the Italian Risiko from scale to control.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1642790551116-18e150f248e3?auto=format&fit=crop&w=800&q=80",
    date: "September 20, 2026",
    read: "11 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/ive-made-the-five-signals-fully-symmetrical-each-now-follows-the-same-structure-what-changed-why-it-matters-decisive-implication",
    title: "I’ve Made the Five Signals Fully Symmetrical: Each Now Follows the Same Structure: What Changed → Why It Matters → Decisive Implication.",
    excerpt: "Who can convert technological acceleration into economic power before the surrounding system slows it down?",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
    date: "September 20, 2026",
    read: "4 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-morning-view-quick-take",
    title: "The Morning View: Quick Take",
    excerpt: "The AI contest has moved from best model to best terms of access — and that final step is now decisive.",
    tag: "Morning View · Strategy",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1444927714506-8492d94b4e3d?auto=format&fit=crop&w=800&q=80",
    date: "September 20, 2026",
    read: "3 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-assurance-stack",
    title: "The Assurance Stack",
    excerpt: "Gemini crosses a cyber boundary, Anthropic moves AI into a wet lab, and Nippon Life readies $12.75B for AI infrastructure—three signals of one shift.",
    tag: "FDK GVI Corporate Benchmark · Capital",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=800&q=80",
    date: "September 20, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/europes-ai-corridors",
    title: "Europe’s AI Corridors",
    excerpt: "Which European corridors can convert compute, energy and capital into self-reinforcing economic velocity — and which have the greatest upside from here.",
    tag: "The Global View · Capital",
    slot: "The Global View",
    image: "https://images.unsplash.com/photo-1454372182658-c712e4c5a1db?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/gvi-countries-rankings-in-focus",
    title: "GVI Countries Rankings: In Focus",
    excerpt: "Which countries are turning accelerated computing, energy, capital and AI into productivity faster than the rest of the world?",
    tag: "Midday Pulse · Macro",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "4 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-acceleration-trap",
    title: "The Acceleration Trap",
    excerpt: "The era of unconstrained AI is ending — and the next divide runs through the AI economy itself.",
    tag: "Quick Take · Capital",
    slot: "Quick Take",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "6 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/central-banks-ai-watch",
    title: "Central Banks & AI Watch",
    excerpt: "The AI Supercycle is producing a monetary paradox as central banks confront a rising neutral rate during the build-out phase.",
    tag: "Midday Pulse · Macro",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "3 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-price-of-scale",
    title: "The Price of Scale",
    excerpt: "The industrial architecture behind the Italian banking battle is becoming visible.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "2 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-quality-of-scale",
    title: "The Quality of Scale",
    excerpt: "The index-level calm at Friday's close masks a consequential repricing of what kind of scale deserves capital.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1504198266287-1659872e6590?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-proof-premium",
    title: "The Proof Premium",
    excerpt: "Anthropic and Accenture commit $2B to AI evaluation, Nscale's contracts hit $103B against a $1.02B loss, Oracle's Jupiter debt trades below par, and Volkswagen resets to a 1% margin.",
    tag: "FDK GVI Corporate Benchmark · Capital",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    date: "September 19, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/europe-ai-gigafactory-watch",
    title: "Europe AI Gigafactory Watch",
    excerpt: "Nabiax breaks ground on an €800M, 80 MW AI data center in Alcalá de Henares, turning announced capacity into physical capex.",
    tag: "The Close · Infrastructure",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    date: "September 18, 2026",
    read: "5 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/the-sovereign-electron",
    title: "The Sovereign Electron",
    excerpt: "The AI Supercycle is no longer financed, powered or secured by corporations alone — sovereign capital has entered the compute stack.",
    tag: "Midday Pulse · Capital",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    date: "September 18, 2026",
    read: "9 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-next-economy-research-center",
    title: "The Next Economy Research Center",
    excerpt: "AI is moving from an output of the R&D system to an input into producing the next generation of AI.",
    tag: "Morning View · AI",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=800&q=80",
    date: "September 18, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-execution-premium",
    title: "The Execution Premium",
    excerpt: "In Italy's banking Risiko, the market is now pricing the path to closing, not the presentation.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
    date: "September 18, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/from-capex-to-collateral",
    title: "From Capex to Collateral",
    excerpt: "As global money converges upward, AI infrastructure crosses the line from expenditure into collateral.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1444927714506-8492d94b4e3d?auto=format&fit=crop&w=800&q=80",
    date: "September 18, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-orchestration-premium",
    title: "The Orchestration Premium",
    excerpt: "Four developments, one system: the competitive bottleneck is migrating from intelligence itself toward the orchestration of everything intelligence requires.",
    tag: "FDK GVI Corporate Benchmark · Capital",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80",
    date: "September 18, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/italian-banking-risiko-the-calendar-becomes-a-weapon",
    title: "Italian Banking Risiko: The Calendar Becomes a Weapon",
    excerpt: "Intesa clears IVASS as antitrust opens a new front — and the calendar becomes part of the capital structure.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    date: "September 17, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-self-tightening-supercycle",
    title: "The Self-tightening Supercycle",
    excerpt: "As the Fed tightens and the 10-year holds near 5%, AI capital formation accelerates into project-finance scale — and starts repricing the resources it consumes.",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80",
    date: "September 17, 2026",
    read: "10 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-sovereign-stack-premium",
    title: "The Sovereign Stack Premium",
    excerpt: "Huawei, SK Hynix, Crux AI, Generac and Cohere show the corporation is no longer competing alone.",
    tag: "FDK GVI Corporate Benchmark · Sovereign Systems",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    date: "September 17, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/global-velocity-index-daily-update",
    title: "Global Velocity Index: Daily Update",
    excerpt: "The Fed lifts rates 25bp to 3.75%–4.00% and signals more, as the US GVI edges to 94.3 and the headline index holds at 108.0.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=80",
    date: "September 17, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-2-16-gigawatt-contradiction",
    title: "The 2.16-gigawatt Contradiction",
    excerpt: "As Anthropic calls to pace frontier models yet builds gigawatts of inference capacity, the Supercycle rotates from creating intelligence to industrializing it.",
    tag: "Midday Pulse · Capital",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?auto=format&fit=crop&w=800&q=80",
    date: "September 16, 2026",
    read: "9 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-next-economy-research-centre",
    title: "The Next Economy Research Centre",
    excerpt: "Training stays concentrated while inference begins to diffuse across regions, enterprises and devices.",
    tag: "Morning View · AI Infrastructure",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80",
    date: "September 16, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-resilience-premium-becomes-measurable",
    title: "The Resilience Premium Becomes Measurable",
    excerpt: "The AI Supercycle is discovering that intelligence is only as valuable as the physical system that can keep it running.",
    tag: "FDK GVI Corporate Benchmark · Infrastructure",
    slot: "FDK GVI Corporate Benchmark",
    image: "https://images.unsplash.com/photo-1504198266287-1659872e6590?auto=format&fit=crop&w=800&q=80",
    date: "September 16, 2026",
    read: "10 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-price-of-permission",
    title: "The Price of Permission",
    excerpt: "Capital is not the constraint on the AI Supercycle — permission is, and it has a price.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?auto=format&fit=crop&w=800&q=80",
    date: "September 16, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-self-reinforcing-risiko",
    title: "The Self-reinforcing Risiko",
    excerpt: "How equity currency, control premiums and time are redrawing the hierarchy of Italian banking.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "5 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/10-year-yield-has-moved-above-5-and-markets-are-assigning-around-a-90-probability-to-a-fed-hike-this-week",
    title: "10-year Yield Has Moved Above 5%, and Markets Are Assigning Around a 90% Probability to a Fed Hike This Week.",
    excerpt: "Higher rates make Italian banking consolidation simultaneously more strategic and more financially demanding.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "2 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/italian-banking-paradox-2-0",
    title: "Italian Banking Paradox 2.0",
    excerpt: "MPS's defence now depends on the value of the very share currency Intesa's takeover attempt helped make scarce.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "12 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/europe-ai-gigafactory-watch-material-inflection-detected",
    title: "Europe AI Gigafactory Watch: Material Inflection Detected",
    excerpt: "Axelera and EUCLYD signal European capital forming around the semiconductor layer just as the continent prepares tens of billions in sovereign AI infrastructure.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1642790551116-18e150f248e3?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "6 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/central-banks-ai-watch-material-inflection-detected",
    title: "Central Banks & AI Watch: Material Inflection Detected",
    excerpt: "Lagarde and the BIS push the AI debate from productivity toward credit, capital and financial stability.",
    tag: "The Close · Central Banks",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "8 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/u-s-china-ai-watch-material-inflection-detected",
    title: "U.S.: China AI Watch: Material Inflection Detected",
    excerpt: "The first clean macroeconomic evidence that China's AI-and-automation strategy is operating at industrial scale.",
    tag: "The Close · Macro",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "5 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/electricity-infrastructure-construction-and-capital",
    title: "Electricity, Infrastructure, Construction and Capital.",
    excerpt: "AI does not eliminate the economics of the physical world — it intensifies them, migrating scarcity from computing to memory to optics to power to capital.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "6 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/the-ai-supercycle-meets-the-scarcity-premium",
    title: "The AI Supercycle Meets the Scarcity Premium",
    excerpt: "Oil above $90, the yen through 160, and Soitec locking in photonics customers — the AI Supercycle is running into scarcity, not out of demand.",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1454372182658-c712e4c5a1db?auto=format&fit=crop&w=800&q=80",
    date: "August 31, 2026",
    read: "10 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/nvidia-won-the-numerator-warsh-now-sets-the-denominator",
    title: "Nvidia Won the Numerator. Warsh Now Sets the Denominator.",
    excerpt: "The Great Split is becoming Earnings Velocity versus Discount-Rate Velocity, and Jackson Hole is today's pivot.",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "6 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/nvidias-340-billion-morning",
    title: "Nvidia’s $340 Billion Morning",
    excerpt: "NVIDIA's results triggered a duration shock — markets are extending the expected life of the AI investment cycle.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80",
    date: "August 27, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-ai-supercycle-meets-the-full-equation",
    title: "The AI Supercycle Meets the Full Equation",
    excerpt: "Three separate market stories — Nvidia earnings, U.S. PCE and the Strait of Hormuz — converge into a single economic equation.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    date: "August 26, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-morning-view",
    title: "The Morning View",
    excerpt: "Two repricing mechanisms converge this week — NVIDIA on the return on intelligence, Jackson Hole on the price of capital.",
    tag: "Midday Pulse · Macro",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "7 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/central-banks-and-the-great-split",
    title: "Central Banks and the Great Split",
    excerpt: "AI is becoming a monetary variable before becoming a monetary-policy target — and central banks were not built for the world it creates.",
    tag: "In Focus · Macro",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?auto=format&fit=crop&w=800&q=80",
    date: "August 19, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/closing-of-the-day",
    title: "Closing of the Day",
    excerpt: "The AI Supercycle is migrating from a technology valuation story into a capital-formation regime.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1504198266287-1659872e6590?auto=format&fit=crop&w=800&q=80",
    date: "August 17, 2026",
    read: "6 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/europes-ai-gigafactory-moment",
    title: "Europe’s AI Gigafactory Moment",
    excerpt: "A cleared Spanish gigafactory joint venture signals Europe is beginning coordinated, large-scale AI capital formation.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1500673922987-e212871fec22?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-bond-market-is-repricing-the-ai-supercycle",
    title: "The Bond Market Is Repricing the AI Supercycle",
    excerpt: "As long-end yields surge worldwide, the AI Supercycle's next bottleneck may be neither chips nor electricity but the risk-free rate itself.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/ai-is-shifting-risk-from-balance-sheets-to-capital-markets",
    title: "AI Is Shifting Risk From Balance Sheets to Capital Markets",
    excerpt: "The AI Supercycle is not slowing — its financial architecture is being rebuilt around distributed risk.",
    tag: "Midday Pulse · Capital",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    date: "August 16, 2026",
    read: "11 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-great-split-reaches-the-demand-side",
    title: "The Great Split Reaches the Demand Side",
    excerpt: "U.S. retail fell, China's credit contracted, Europe's employment barely grew — yet capital keeps flooding into the AI trade.",
    tag: "The Close · Macro",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    date: "August 14, 2026",
    read: "10 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/repricing-the-cost-of-capital",
    title: "Repricing the Cost of Capital",
    excerpt: "As producer prices hold and yields fall, the AI trade is migrating from equities into credit — and toward a single emerging capital cycle.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1642790551116-18e150f248e3?auto=format&fit=crop&w=800&q=80",
    date: "August 13, 2026",
    read: "5 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/who-earns-the-return-on-a-trillion-dollars-of-ai",
    title: "Who Earns the Return on a Trillion Dollars of AI?",
    excerpt: "Global AI investment now exceeds $1 trillion in 2026, forcing markets to ask who actually earns the return.",
    tag: "Midday Pulse · Capital",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80",
    date: "August 12, 2026",
    read: "5 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-great-split-is-now-capital-formation-vs-demand",
    title: "The Great Split Is Now Capital Formation vs. Demand",
    excerpt: "Three economies, one phenomenon — capital formation is decoupling from the demand meant to absorb it.",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-ai-trade-is-repricing-the-worlds-cost-of-capital",
    title: "The AI Trade Is Repricing the World’s Cost of Capital",
    excerpt: "Hyperscaler bond issuance is lifting real yields and reshaping the cost of capital for the entire economy.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
    date: "August 14, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/part-i-the-return-of-pricing-power",
    title: "Part I — The Return of Pricing Power",
    excerpt: "A quiet session masked a structural shift as capital rotates toward the owners of the Industrial AI ecosystem.",
    tag: "The Close · Capital",
    slot: "The Close",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
    date: "August 3, 2026",
    read: "3 min read",
    time: "21:00",
    kind: "night"
  },
  {
    url: "/the-ai-rally-is-no-longer-about-ai",
    title: "The AI Rally Is No Longer About AI",
    excerpt: "A benign CPI print rewarded not tech broadly but the industrial architecture of intelligence — and the valuation regime is turning selective.",
    tag: "The Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/ai-has-found-its-bankers",
    title: "AI Has Found Its Bankers",
    excerpt: "Nvidia enlists six of the world's largest financial institutions to fund Industrial AI at system scale, as oil, permits and CPI reintroduce physical limits.",
    tag: "The Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=800&q=80",
    date: "August 11, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/ai-infrastructure-is-entering-a-higher-cost-financing-regime",
    title: "AI Infrastructure Is Entering a Higher-Cost Financing Regime",
    excerpt: "Debt issuance is accelerating and project bankability is tightening as markets begin to distinguish capital committed from capital capable of earning above its cost.",
    tag: "Midday Pulse · Capital",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1444927714506-8492d94b4e3d?auto=format&fit=crop&w=800&q=80",
    date: "August 10, 2026",
    read: "9 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-great-split-becomes-a-capital-regime",
    title: "The Great Split Becomes a Capital Regime",
    excerpt: "Labor formation is slowing while capital formation accelerates — the defining variable of the Age of Industrial AI.",
    tag: "The Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    date: "August 9, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-grid-draws-the-line",
    title: "The Grid Draws the Line",
    excerpt: "The AI Supercycle is not weakening—it is becoming industrial, and therefore more selective.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80",
    date: "August 5, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-european-railways-competitive-dynamics",
    title: "The European Railways Competitive Dynamics",
    excerpt: "Why the next phase of European rail competition is a contest between capital architectures, not train operators.",
    tag: "In Focus · Capital",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=800&q=80",
    date: "September 15, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-age-of-industrial-ai-is-becoming-the-age-of-capital-formation",
    title: "The Age of Industrial AI Is Becoming the Age of Capital Formation",
    excerpt: "Weak payrolls, Nvidia's infrastructure push and Hormuz all point to the same divide — capital-rich versus capital-constrained systems.",
    tag: "The Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1454372182658-c712e4c5a1db?auto=format&fit=crop&w=800&q=80",
    date: "August 8, 2026",
    read: "2 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-ai-trade-has-split-into-cash-flow-and-capex",
    title: "The AI Trade Has Split Into Cash Flow and Capex",
    excerpt: "Microsoft didn't rescue the AI trade — it proved that only companies with contracted demand, operating leverage and defensible cash flow deserve to remain inside it. The Great Split has moved inside Artificial Intelligence itself.",
    tag: "Midday Pulse · Markets",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    date: "July 30, 2026",
    read: "11 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-cost-of-velocity-has-arrived",
    title: "The Cost of Velocity Has Arrived",
    excerpt: "The overnight semiconductor rout does not end the AI Supercycle — it ends the assumption that every dollar spent to build it creates equal value. The market has moved from measuring possibility to underwriting reality.",
    tag: "Morning View · Markets",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=80",
    date: "July 29, 2026",
    read: "10 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-great-acceleration-meets-the-cost-of-capital",
    title: "The Great Acceleration Meets the Cost of Capital",
    excerpt: "As renewed inflation risks and a possible Federal Reserve rate increase raise the cost of capital, markets must separate acceleration supported by strategic necessity from acceleration sustained only by optimistic valuations.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1500673922987-e212871fec22?auto=format&fit=crop&w=800&q=80",
    date: "July 27, 2026",
    read: "14 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/from-supplier-to-architect",
    title: "From Supplier to Architect",
    excerpt: "The FDK Global Velocity Index rises to 107.0 (+0.09%) on 26 July 2026. Today's revision is almost entirely South Korea, where a Samsung–Broadcom MOU and an SK–Nvidia initiative — roughly $950bn of announced agreements — signal a shift from semiconductor leadership toward system-level AI architecture.",
    tag: "Daily Nowcast · Global Velocity Index",
    slot: "Daily Nowcast",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?auto=format&fit=crop&w=800&q=80",
    date: "July 26, 2026",
    read: "5 min read",
    time: "07:00",
    kind: "day"
  },
  {
    url: "/the-velocity-broadens",
    title: "The Velocity Broadens",
    excerpt: "The FDK Global Velocity Index nowcast for 25 July 2026 reads 106.9, up 0.09%. The principal move is a material upgrade to South Korea, with smaller positive revisions to China, Japan and Germany — the AI Supercycle is beginning to broaden into a distributed industrial architecture.",
    tag: "Daily Nowcast · Global Velocity Index",
    slot: "Daily Nowcast",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80",
    date: "July 25, 2026",
    read: "7 min read",
    time: "07:00",
    kind: "day"
  },
  {
    url: "/the-illusion-of-relief",
    title: "The Illusion of Relief",
    excerpt: "Markets are rebounding, but the operating environment is not normalising — oil relief masks impaired sea lanes, narrow leadership and a weakening policy put.",
    tag: "Midday Pulse · Markets",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1504198266287-1659872e6590?auto=format&fit=crop&w=800&q=80",
    date: "July 24, 2026",
    read: "8 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-price-of-velocity",
    title: "The Price of Velocity",
    excerpt: "Oil approaches $100, bond yields break higher, and markets demand proof that industrial AI can generate returns as rapidly as it consumes capital.",
    tag: "Midday Pulse · Markets",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    date: "July 23, 2026",
    read: "8 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/waiting-for-proof",
    title: "Waiting for Proof",
    excerpt: "The AI Supercycle has entered its second phase, where capital discipline matters as much as technological leadership.",
    tag: "Midday Pulse · Markets",
    slot: "Midday Pulse",
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?auto=format&fit=crop&w=800&q=80",
    date: "July 22, 2026",
    read: "3 min read",
    time: "12:30",
    kind: "day"
  },
  {
    url: "/the-global-industries-benchmark",
    title: "The Global Industries Benchmark",
    excerpt: "The FDK GVI Global Industries Benchmark ranks 15 sectors on 22 July 2026. AI holds the top spot at 96.2, but the deeper story is capital migrating upstream — from models to chips to data centers to power and raw materials.",
    tag: "Market Watch · Benchmark",
    slot: "Market Watch",
    image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=800&q=80",
    date: "July 22, 2026",
    read: "7 min read",
    time: "09:30",
    kind: "day"
  },
  {
    url: "/the-great-divergence",
    title: "The Great Divergence",
    excerpt: "The AI Supercycle is driving the largest and fastest redistribution of economic power since the Industrial Revolution — producing faster winners and permanent laggards.",
    tag: "Market Watch · Markets",
    slot: "Market Watch",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    date: "July 21, 2026",
    read: "7 min read",
    time: "09:30",
    kind: "day"
  },
  {
    url: "/the-architecture-of-the-next-economy",
    title: "The Architecture of the Next Economy",
    excerpt: "A new framework for the Age of Artificial Intelligence: as innovation ceases to be scarce, national advantage will belong to the economies that orchestrate science, capital, energy and institutions best.",
    tag: "In Focus · Macro",
    slot: "In Focus",
    image: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=800&q=80",
    date: "July 20, 2026",
    read: "3 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-age-of-moonshots",
    title: "The Age of Moonshots",
    excerpt: "Artificial intelligence is not the defining technology of our time — it is the catalyst. The deeper transformation is that humanity has entered the Age of Moonshots.",
    tag: "Sunday Edition · Macro",
    slot: "Sunday Edition",
    image: "https://images.unsplash.com/photo-1642790551116-18e150f248e3?auto=format&fit=crop&w=800&q=80",
    date: "July 19, 2026",
    read: "4 min read",
    time: "09:00",
    kind: "day"
  },
  {
    url: "/the-race-for-the-next-economy",
    title: "The Race for the Next Economy",
    excerpt: "A new global race has begun — not for territory or commodities, but for where the Next Economy will be built, and whether Europe can mobilize capital before it migrates elsewhere.",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?auto=format&fit=crop&w=800&q=80",
    date: "July 18, 2026",
    read: "5 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-new-alpha",
    title: "The New Alpha",
    excerpt: "The next trillion dollars will not be created by better technology, but by higher productivity — the speed at which nations convert intelligence into output.",
    tag: "Morning View · Productivity",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1483058712412-4245e9b90334?auto=format&fit=crop&w=800&q=80",
    date: "July 17, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-great-split-is-accelerating",
    title: "The Great Split Is Accelerating",
    excerpt: "From Hormuz to TSMC, capital is reorganizing around competing AI ecosystems — where resilience, industrial capability and sovereignty matter more than efficiency.",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=800&q=80",
    date: "July 16, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-great-split",
    title: "The Great Split",
    excerpt: "Why the AI Supercycle is creating a K-shaped global economy — one side builds intelligence and compounds capital, the other imports it and rents access.",
    tag: "Morning View · Macro",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80",
    date: "July 15, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-next-trillion-dollar-trade",
    title: "The Next Trillion-Dollar Trade",
    excerpt: "Forget oil. The real investment opportunity is the global race to finance intelligence — $5.8 trillion to build the infrastructure the AI economy runs on.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80",
    date: "July 14, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-end-of-cheap-globalization",
    title: "The End of Cheap Globalization",
    excerpt: "A new capital cycle is emerging around AI, defense, energy and industrial sovereignty — the largest reallocation of capital since the end of the Cold War.",
    tag: "Morning View · Geopolitics",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&w=800&q=80",
    date: "July 13, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/intelligence-becomes-infrastructure",
    title: "Intelligence Becomes Infrastructure",
    excerpt: "Hormuz threatens the rate-cut trade, AI is turning electricity into a scarce financial asset, and Europe — with Spain its rising star — may be the most under-owned beneficiary.",
    tag: "Morning View · Energy",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80",
    date: "July 12, 2026",
    read: "9 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-end-of-the-technology-cycle",
    title: "The End of the Technology Cycle",
    excerpt: "AI is becoming a permanent claim on capital, energy and political power. Markets are still treating it as another trade.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    date: "July 11, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-next-security-order",
    title: "The Next Security Order",
    excerpt: "The market is pricing oil. It should be pricing the next security order — every crisis reallocates capital, and this one reallocates it toward resilience.",
    tag: "Breaking News · Geopolitics",
    slot: "Breaking News",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=800&q=80",
    date: "July 8, 2026",
    read: "6 min read",
    time: "13:30",
    kind: "day"
  },
  {
    url: "/the-intelligence-divide",
    title: "The Intelligence Divide",
    excerpt: "Capital is no longer rewarding companies — it is separating the owners of intelligence infrastructure from everyone else.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
    date: "July 7, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-new-capital-cycle",
    title: "The New Capital Cycle",
    excerpt: "The greatest opportunity is no longer AI — it is the race to own the Infrastructure of Intelligence. History rewards the landlords, not the tenants.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    date: "July 6, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-second-ai-supercycle",
    title: "The Second AI Supercycle",
    excerpt: "Intelligence created the boom. Infrastructure will create the fortunes — capital is rotating toward the Infrastructure of Intelligence.",
    tag: "Morning View · Infrastructure",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
    date: "June 30, 2026",
    read: "7 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-great-capital-formation-race",
    title: "The Great Capital Formation Race",
    excerpt: "Why the next AI winners will be determined less by innovation than by investment — the largest capital formation cycle of the century is underway.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
    date: "June 29, 2026",
    read: "5 min read",
    time: "08:30",
    kind: "day"
  },
  {
    url: "/beyond-the-ai-trade",
    title: "Beyond the AI Trade",
    excerpt: "The next trillion dollars won’t be created by better models — it will be created by better capital allocation. AI is entering its execution phase.",
    tag: "The Week Ahead · Capital",
    slot: "The Week Ahead",
    image: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=800&q=80",
    date: "June 28, 2026",
    read: "6 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-ai-reckoning-begins",
    title: "The AI Reckoning Begins",
    excerpt: "Markets are repricing the winners before the economy does — the era when any AI narrative earned a premium is ending.",
    tag: "Morning View · Markets",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
    date: "June 26, 2026",
    read: "3 min read",
    time: "08:45",
    kind: "day"
  },
  {
    url: "/the-great-ai-shakeout",
    title: "The Great AI Shakeout",
    excerpt: "Why capital is no longer rewarding AI exposure — it is rewarding AI economics. From enthusiasm to discipline.",
    tag: "Morning View · Markets",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    date: "June 26, 2026",
    read: "7 min read",
    time: "08:30",
    kind: "day"
  },
  {
    url: "/the-deflationary-rotation",
    title: "The Deflationary Rotation",
    excerpt: "Why the next phase of the AI supercycle will be about lower costs, higher margins and rising profits — not bigger models.",
    tag: "Today’s Edition · Macro",
    slot: "Today’s Edition",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    date: "June 23, 2026",
    read: "8 min read",
    time: "08:00",
    kind: "day"
  },
  {
    url: "/the-velocity-imperative",
    title: "The Velocity Imperative",
    excerpt: "Why speed — not scale — has become the decisive competitive variable, and the three questions most boards are not yet asking.",
    tag: "Morning View · Strategy",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=800&q=80",
    date: "June 19, 2026",
    read: "4 min read",
    time: "07:45",
    kind: "day"
  },
  {
    url: "/structural-bifurcation",
    title: "Structural Bifurcation",
    excerpt: "The divergence your board has not yet named — between organisations that embed intelligence and those building it for their vendors.",
    tag: "Night Briefing · Governance",
    slot: "Night Briefing",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    date: "June 12, 2026",
    read: "4 min read",
    time: "21:30",
    kind: "night"
  },
  {
    url: "/the-repricing",
    title: "The Repricing",
    excerpt: "What European infrastructure is actually worth once it learns — and why standard valuation models have not yet absorbed it.",
    tag: "Morning View · Capital",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80",
    date: "June 4, 2026",
    read: "5 min read",
    time: "08:10",
    kind: "day"
  },
  {
    url: "/on-sovereign-intelligence",
    title: "On Sovereign Intelligence",
    excerpt: "Why Europe's AI position is an infrastructure governance question — three models, one structural choice being written right now.",
    tag: "Night Briefing · Europe",
    slot: "Night Briefing",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    date: "May 27, 2026",
    read: "4 min read",
    time: "22:00",
    kind: "night"
  },
  {
    url: "/the-fiscal-architecture",
    title: "The Fiscal Architecture of the Velocity Economy",
    excerpt: "What governments must relearn about capital before the instruments harden — sequenced finance for assets that learn, not depreciate.",
    tag: "Morning View · Policy",
    slot: "Morning View",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80",
    date: "May 19, 2026",
    read: "4 min read",
    time: "07:30",
    kind: "day"
  },
  {
    url: "/what-the-velocity-economy-demands",
    title: "What the Velocity Economy Demands from Capital",
    excerpt: "Infrastructure funds are pricing AI-native operators as utilities. How to tell a genuine learning system from an AI narrative.",
    tag: "Night Briefing · Capital",
    slot: "Night Briefing",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    date: "May 12, 2026",
    read: "3 min read",
    time: "21:00",
    kind: "night"
  }
];


















