/* FDK EmpowerNet · 10-year-yield-has-moved-above-5-and-markets-are-assigning-around-a-90-probability-to-a-fed-hike-this-week · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"The Velocity Edge":"The Velocity Edge"});
