/* FDK EmpowerNet · 128-bps-next-week-is-about-contagion-not-italy · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"The Velocity Edge":"The Velocity Edge"});
