/* FDK EmpowerNet · 15-september-2026 · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Europe":"Europa","The Three Speed Limits":"I tre limiti di velocità","The Velocity Edge":"The Velocity Edge"});
