/* FDK EmpowerNet · 15-september-2026 · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Europe":"Europa","The Three Speed Limits":"Los tres límites de velocidad","The Velocity Edge":"The Velocity Edge"});
