/* FDK EmpowerNet · 16-september-2026-provisional-nowcast · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"FDK Global Velocity Index":"FDK Global Velocity Index","The Velocity Edge":"The Velocity Edge"});
