/* FDK EmpowerNet · 16-september-2026-provisional-nowcast · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"FDK Global Velocity Index":"FDK Global Velocity Index","The Velocity Edge":"The Velocity Edge"});
