/* FDK EmpowerNet · 21-september-2026 · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Brent":"Brent","The Velocity Edge":"The Velocity Edge","U.S. 10-year Treasury yield":"Rendimento del Treasury statunitense a 10 anni"});
