/* FDK EmpowerNet · ai-is-moving-from-a-valuation-story-to-a-credit-and-cash-flow-story · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"The Velocity Edge":"The Velocity Edge"});
