/* FDK EmpowerNet · europe-watch · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Europe Watch":"Observatorio de Europa","THE NEW METRIC":"LA NUEVA MÉTRICA","The Velocity Edge":"The Velocity Edge"});
