/* FDK EmpowerNet · europe-ai-gigafactory-watch · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Europe AI Gigafactory Watch":"Observatorio de gigafábricas de IA en Europa","The Velocity Edge":"The Velocity Edge"});
