/* FDK EmpowerNet · europe-watch · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Europe Watch":"Osservatorio Europa","THE NEW METRIC":"LA NUOVA METRICA","The Velocity Edge":"The Velocity Edge"});
