/* FDK EmpowerNet · hola-esta-es-una-segunda-prueba-del-24-de-septiembre · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Capital":"Capitale","Macro":"Macro","The Velocity Edge":"The Velocity Edge"});
