/* FDK EmpowerNet · hola-esta-es-una-segunda-prueba-del-24-de-septiembre · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Capital":"Capital","Macro":"Macro","The Velocity Edge":"The Velocity Edge"});
