/* FDK EmpowerNet · https-chatgpt-com-library-share-libfile-a9ec4035b3d88191b6dda0d718a5fa00-account-id-personal · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"The Velocity Edge":"The Velocity Edge"});
