/* FDK EmpowerNet · id-make-the-thesis-one-step-more-forceful-ai-is-already-acting-like-a-tightening-shock-through-capital-formation-while-the-easing-effect-of-productivity-remains-delayed · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"The Velocity Edge":"The Velocity Edge"});
