/* FDK EmpowerNet · intelligence-library-preview-dashboard · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"FDK Velocity Dashboard":"Cruscotto Velocity di FDK","In Focus":"In primo piano","Indices":"Indici","Market":"Mercato","Midday Pulse":"Polso di mezzogiorno","Next Economy":"Prossima Economia","Rankings":"Classifiche","The Close":"La chiusura","Today":"Oggi","Velocity":"Velocità"});
