/* FDK EmpowerNet · intelligence-library-preview-dashboard · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"FDK Velocity Dashboard":"Panel de velocidad de FDK","In Focus":"En foco","Indices":"Índices","Market":"Mercado","Midday Pulse":"Pulso de mediodía","Next Economy":"Próxima Economía","Rankings":"Clasificaciones","The Close":"El cierre","Today":"Hoy","Velocity":"Velocidad"});
