/* FDK EmpowerNet · ive-made-the-five-signals-fully-symmetrical-each-now-follows-the-same-structure-what-changed-why-it-matters-decisive-implication · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"The Velocity Edge":"The Velocity Edge"});
