/* FDK EmpowerNet · markets-technology-geopolitics-the-real-economy · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Geopolitics":"Geopolítica","Markets":"Mercados","Technology":"Tecnología","The Velocity Edge":"The Velocity Edge"});
