/* FDK EmpowerNet · markets-technology-geopolitics-the-real-economy · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Geopolitics":"Geopolitica","Markets":"Mercati","Technology":"Tecnologia","The Velocity Edge":"The Velocity Edge"});
