/* FDK EmpowerNet · material-inflection-detected · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Central Banks & AI Watch":"Observatorio de bancos centrales e IA","The Velocity Edge":"The Velocity Edge"});
