/* FDK EmpowerNet · material-inflection-detected · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Central Banks & AI Watch":"Osservatorio banche centrali e IA","The Velocity Edge":"The Velocity Edge"});
