/* FDK EmpowerNet · provisional-nowcast · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"FDK Global Velocity Index":"Indice Globale di Velocità FDK","THE PARADOX":"IL PARADOSSO","The Velocity Edge":"The Velocity Edge","Weighted Global Velocity Index (2025=100), unchanged":"Indice Globale di Velocità ponderato (2025=100), invariato"});
