/* FDK EmpowerNet · provisional-nowcast · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"FDK Global Velocity Index":"Índice Global de Velocidad FDK","THE PARADOX":"LA PARADOJA","The Velocity Edge":"The Velocity Edge","Weighted Global Velocity Index (2025=100), unchanged":"Índice Global de Velocidad ponderado (2025=100), sin cambios"});
