/* FDK EmpowerNet · publicacion-de-nota-numero-1-prueba-del-24-de-septiembre-del-2026 · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Capital":"Capital","Macro":"Macro","The Velocity Edge":"The Velocity Edge"});
