/* FDK EmpowerNet · the-great-split-becomes-a-capital-regime · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"The Great Split":"The Great Split","The Velocity Edge":"The Velocity Edge"});
