/* FDK EmpowerNet · the-ai-trade-has-split-into-cash-flow-and-capex · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Sovereign Capital":"Capital soberano","The Velocity Edge":"The Velocity Edge"});
