/* FDK EmpowerNet · the-855-billion-capacity-divide · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Capital":"Capital","The Velocity Edge":"The Velocity Edge"});
