/* FDK EmpowerNet · the-economics-of-the-bottleneck · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Capital Formation":"Formación de capital","Infrastructure Position":"Posición en infraestructura","Productivity Acceleration":"Aceleración de la productividad","Resilience":"Resiliencia","The Velocity Edge":"The Velocity Edge"});
