/* FDK EmpowerNet · the-private-capital-vote · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Continental Bifurcation":"Bifurcación continental","The Velocity Edge":"The Velocity Edge"});
