/* FDK EmpowerNet · the-ai-trade-has-split-into-cash-flow-and-capex · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"AI and Accelerated Computing":"IA y computación acelerada","Banking and Credit Formation":"Banca y formación de crédito","Energy and Power Infrastructure":"Infraestructura energética y eléctrica","Geopolitical Friction":"Fricción geopolítica","Sovereign Capital":"Capital soberano","The Velocity Edge":"The Velocity Edge"});
