/* FDK EmpowerNet · the-855-billion-capacity-divide · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Capital":"Capitale","The Velocity Edge":"The Velocity Edge"});
