/* FDK EmpowerNet · the-morning-view-quick-take · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"The Great Split":"La Grande Scissione","The Velocity Edge":"The Velocity Edge"});
