/* FDK EmpowerNet · the-ai-trade-has-split-into-cash-flow-and-capex · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Sovereign Capital":"Capitale sovrano","The Velocity Edge":"The Velocity Edge"});
