/* FDK EmpowerNet · the-ai-economics-test · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Cellnex":"Cellnex","The Velocity Edge":"The Velocity Edge"});
