/* FDK EmpowerNet · the-136-and-144-action-triggers-in-focus · ES — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.es=window.FDK_I18N.es||{};
Object.assign(window.FDK_I18N.es,{"Signal":"Señal","The Velocity Edge":"The Velocity Edge"});
