/* FDK EmpowerNet · the-economics-of-the-bottleneck · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"Capital Formation":"Formazione di capitale","Infrastructure Position":"Posizione infrastrutturale","Productivity Acceleration":"Accelerazione della produttività","Resilience":"Resilienza","The Velocity Edge":"The Velocity Edge"});
