/* FDK EmpowerNet · two-systems-two-economics-one-supercycle · IT — generated by scripts/i18n-build.mjs. Do not edit by hand. */
window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.it=window.FDK_I18N.it||{};
Object.assign(window.FDK_I18N.it,{"The Second-Order Effect":"L'effetto di secondo ordine","The Velocity Edge":"The Velocity Edge"});
