#!/usr/bin/env node
/* ============================================================
   FDK · GVI build step
   Reads the canonical source data (data/gvi/latest.json) and
   emits the browser bundle gvi-data.js (window.GVI_DATA = …).

   The static site loads gvi-data.js directly (no fetch / CORS,
   works on file://). This script is the ONLY thing that writes
   gvi-data.js — never edit that file by hand.

   Usage:  node scripts/gvi-build.mjs
   ============================================================ */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "data", "gvi", "latest.json");
const OUT = join(ROOT, "gvi-data.js");

/* ---- minimal validation ---- */
function fail(msg) { console.error("✗ GVI build:", msg); process.exit(1); }

let data;
try { data = JSON.parse(readFileSync(SRC, "utf8")); }
catch (e) { fail("cannot read/parse " + SRC + " — " + e.message); }

if (!data.meta || !data.meta.updated) fail("meta.updated is required");
if (!data.daily || !data.daily.countries) fail("daily.countries is required");

const TREND = new Set(["up", "flat", "down"]);
let warnings = 0;
function checkRows(label, rows, fields) {
  if (!Array.isArray(rows)) return;
  rows.forEach((r, i) => {
    fields.forEach((f) => {
      if (r[f] === undefined) { console.warn(`  ! ${label}[${i}] missing "${f}"`); warnings++; }
    });
    if (r.trend && !TREND.has(r.trend)) { console.warn(`  ! ${label}[${i}] bad trend "${r.trend}"`); warnings++; }
    if (typeof r.score === "number" && (r.score < 0 || r.score > 120)) { console.warn(`  ! ${label}[${i}] score out of range: ${r.score}`); warnings++; }
  });
}
checkRows("daily.countries", data.daily.countries.rows, ["rank", "name", "score"]);
if (data.daily.corporates) {
  checkRows("daily.corporates.top", data.daily.corporates.top, ["rank", "name", "score"]);
  checkRows("daily.corporates.bottom", data.daily.corporates.bottom, ["rank", "name", "score"]);
}

/* ---- emit browser bundle ---- */
const banner =
`/* AUTO-GENERATED by scripts/gvi-build.mjs — DO NOT EDIT BY HAND.
   Edit data/gvi/latest.json (or run the ingest pipeline), then:
     node scripts/gvi-build.mjs
   Source data as of ${data.meta.updated}. */\n`;

const body = "window.GVI_DATA = " + JSON.stringify(data, null, 2) + ";\n";
writeFileSync(OUT, banner + body);

console.log(`✓ GVI build: wrote ${OUT} (as of ${data.meta.updated})`);
console.log(`  countries: ${data.daily.countries.rows.length}` +
  (data.daily.corporates ? `, corporates: ${data.daily.corporates.top.length}+${data.daily.corporates.bottom.length}` : "") +
  (data.weekly?.industries ? `, industries: ${data.weekly.industries.industries.length}` : "") +
  (data.weekly?.europe ? `, europe: ${data.weekly.europe.countries.length}` : "") +
  (data.weekly?.banks ? `, banks-countries: ${data.weekly.banks.countries.length}` : ""));
if (warnings) console.log(`  ${warnings} warning(s) — review above.`);
