#!/usr/bin/env node
/* ============================================================
   FDK · i18n dictionary build

   Turns the two editable sources — data/i18n/es.json and
   data/i18n/it.json — into the files the browser loads:

     i18n/common.<lang>.js   strings shared by several pages
     i18n/<slug>.<lang>.js   strings that belong to one page

   Splitting them this way keeps a Spanish or Italian reader from
   downloading the whole site's copy to read a single note.

     node scripts/i18n-build.mjs           → build + report
     node scripts/i18n-build.mjs --check   → report only, non-zero on gaps
   ============================================================ */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from "node:fs";
import { join, resolve, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { extractAll, extractJS, htmlFiles, noTranslate } from "./i18n-extract.mjs";
import { resolves } from "./i18n-core.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "data", "i18n");
const OUT = join(ROOT, "i18n");
const LANGS = ["es", "it"];

export function slugFor(relPath) {
  const s = relPath.replace(/index\.html$/i, "").replace(/^\/+|\/+$/g, "");
  return s === "" ? "home" : s.replace(/\//g, "-").toLowerCase();
}

function readJSON(p, fallback) {
  return existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : fallback;
}

/* Keys that reach the DOM through JS (posts.js, script.js) and the
   handful of labels the engine builds itself — always in common. */
function runtimeKeys() {
  const extra = readJSON(join(SRC, "runtime.json"), []);
  return new Set([...extractJS().keys(), ...extra]);
}

export function buildIndex() {
  const all = extractAll();
  const rt = runtimeKeys();
  for (const k of rt) if (!all.has(k)) all.set(k, { files: new Set(["runtime"]), kinds: new Set(["runtime"]) });

  const common = new Set();
  const perPage = new Map();          // slug -> Set(key)
  for (const f of htmlFiles()) perPage.set(slugFor(relative(ROOT, f)), new Set());

  for (const [k, v] of all) {
    const slugs = new Set([...v.files].filter((f) => f !== "runtime" && f !== "posts.js").map(slugFor));
    if (rt.has(k) || slugs.size !== 1) { common.add(k); continue; }
    const only = [...slugs][0];
    if (!perPage.has(only)) perPage.set(only, new Set());
    perPage.get(only).add(k);
  }
  return { all, common, perPage };
}

function emit(lang, name, keys, dict) {
  const obj = {};
  for (const k of [...keys].sort()) if (dict[k] !== undefined) obj[k] = dict[k];
  if (!Object.keys(obj).length) return 0;
  const body =
    `/* FDK EmpowerNet · ${name} · ${lang.toUpperCase()} — generated by scripts/i18n-build.mjs. Do not edit by hand. */\n` +
    `window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.${lang}=window.FDK_I18N.${lang}||{};\n` +
    `Object.assign(window.FDK_I18N.${lang},${JSON.stringify(obj)});\n`;
  writeFileSync(join(OUT, `${name}.${lang}.js`), body);
  return Object.keys(obj).length;
}

const isCLI = process.argv[1] && process.argv[1].endsWith("i18n-build.mjs");
if (isCLI) main();

function main() {
const check = process.argv.includes("--check");
const { all, common, perPage } = buildIndex();

if (!check) {
  if (existsSync(OUT)) rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
}

let bad = 0;
for (const lang of LANGS) {
  const dict = readJSON(join(SRC, `${lang}.json`), {});
  const keep = noTranslate();
  const missing = [...all.keys()].filter((k) => !keep.has(k) && !resolves(k, dict));
  const stale = Object.keys(dict).filter((k) => !all.has(k));
  if (missing.length) bad = 1;
  if (!check) {
    let n = emit(lang, "common", common, dict);
    let pages = 0;
    for (const [slug, keys] of perPage) {
      const c = emit(lang, slug, keys, dict);
      if (c) { n += c; pages++; }
    }
    console.log(`${lang}: ${n} strings → common + ${pages} page files`);
  }
  const translatable = all.size - [...all.keys()].filter((k) => keep.has(k)).length;
  console.log(`${lang}: ${translatable - missing.length}/${translatable} translated` +
    (missing.length ? `  · MISSING ${missing.length}` : "  · complete") +
    (stale.length ? `  · stale ${stale.length}` : ""));
}
if (check && bad) process.exit(1);
}
