#!/usr/bin/env node
/* ============================================================
   FDK · i18n dictionary build

   Turns the two editable sources — data/i18n/es.json and
   data/i18n/it.json — into the files the browser loads:

     i18n/common.<lang>.js   strings shared by several pages
     i18n/<slug>.<lang>.js   strings that belong to one page

   Splitting them this way keeps a Spanish or Italian reader from
   downloading the whole site's copy to read a single note.

     node scripts/i18n-build.mjs           → build + report
     node scripts/i18n-build.mjs --check   → report only, non-zero on gaps
   ============================================================ */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, resolve, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { extractAll, extractJS, htmlFiles, noTranslate } from "./i18n-extract.mjs";
import { resolves, lookupParts } from "./i18n-core.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "data", "i18n");
const OUT = join(ROOT, "i18n");
const LANGS = ["es", "it"];

export function slugFor(relPath) {
  const s = relPath.replace(/index\.html$/i, "").replace(/^\/+|\/+$/g, "");
  return s === "" ? "home" : s.replace(/\//g, "-").toLowerCase();
}

function readJSON(p, fallback) {
  return existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : fallback;
}

/* Keys that reach the DOM through JS (posts.js, script.js) and the
   handful of labels the engine builds itself — always in common. */
function runtimeKeys() {
  const extra = readJSON(join(SRC, "runtime.json"), []);
  return new Set([...extractJS().keys(), ...extra]);
}

export function buildIndex() {
  const all = extractAll();
  const rt = runtimeKeys();
  for (const k of rt) if (!all.has(k)) all.set(k, { files: new Set(["runtime"]), kinds: new Set(["runtime"]) });

  const common = new Set();
  const perPage = new Map();          // slug -> Set(key)
  for (const f of htmlFiles()) perPage.set(slugFor(relative(ROOT, f)), new Set());

  for (const [k, v] of all) {
    const slugs = new Set([...v.files].filter((f) => f !== "runtime" && f !== "posts.js").map(slugFor));
    if (rt.has(k) || slugs.size !== 1) { common.add(k); continue; }
    const only = [...slugs][0];
    if (!perPage.has(only)) perPage.set(only, new Set());
    perPage.get(only).add(k);
  }
  /* A block the engine translates part by part needs those parts shipped
     with it, even though they are not keys of their own. */
  const attach = (bucket, k) => { for (const t of lookupParts(k)) bucket.add(t); };
  for (const k of [...common]) attach(common, k);
  for (const keys of perPage.values()) for (const k of [...keys]) attach(keys, k);

  return { all, common, perPage };
}

function emit(lang, name, keys, dict) {
  const obj = {};
  for (const k of [...keys].sort()) if (dict[k] !== undefined) obj[k] = dict[k];
  if (!Object.keys(obj).length) return 0;
  const body =
    `/* FDK EmpowerNet · ${name} · ${lang.toUpperCase()} — generated by scripts/i18n-build.mjs. Do not edit by hand. */\n` +
    `window.FDK_I18N=window.FDK_I18N||{};window.FDK_I18N.${lang}=window.FDK_I18N.${lang}||{};\n` +
    `Object.assign(window.FDK_I18N.${lang},${JSON.stringify(obj)});\n`;
  writeFileSync(join(OUT, `${name}.${lang}.js`), body);
  return Object.keys(obj).length;
}

/* ------------------------------------------------------------------
   Cache busting. The browser caches /i18n/*.js under the ?v= query in
   i18n-boot.js, so a dictionary that changes without that query changing
   is served stale — the shell translates from the old cache while new
   copy stays English. Deriving the version from the built content makes
   that impossible: any change to a dictionary or to the scripts that
   read one produces a new version on the next build.
   ------------------------------------------------------------------ */
const VERSIONED = ["i18n-boot.js", "i18n.js", "script.js", "posts.js",
  "market.js", "market-board.js", "gvi.js", "gvi-data.js", "styles.css"];

function assetVersion() {
  const h = createHash("sha256");
  for (const f of readdirSync(OUT).sort()) h.update(readFileSync(join(OUT, f)));
  for (const f of VERSIONED) {
    const p = join(ROOT, f);
    if (!existsSync(p)) continue;
    /* normalise the version strings out, or the hash would chase itself */
    h.update(readFileSync(p, "utf8").replace(/\?v=[0-9a-z]+/g, "?v=").replace(/var V = "[^"]*";/, ""));
  }
  return "v=" + h.digest("hex").slice(0, 10);
}

function stampVersion(version) {
  let touched = 0;
  const boot = join(ROOT, "i18n-boot.js");
  const b = readFileSync(boot, "utf8");
  const nb = b.replace(/var V = "[^"]*";/, `var V = "${version}";`);
  if (nb !== b) { writeFileSync(boot, nb); touched++; }

  const rx = new RegExp(`((?:src|href)="/(?:${VERSIONED.map((f) => f.replace(".", "\\.")).join("|")})\\?v=)[0-9a-z=]*(")`, "g");
  for (const f of htmlFiles()) {
    const src = readFileSync(f, "utf8");
    const out = src.replace(rx, (m, a, b2) => a.replace(/v=$/, "") + version + b2);
    if (out !== src) { writeFileSync(f, out); touched++; }
  }
  return touched;
}

const isCLI = process.argv[1] && process.argv[1].endsWith("i18n-build.mjs");
if (isCLI) main();

function main() {
const check = process.argv.includes("--check");
const { all, common, perPage } = buildIndex();

if (!check) {
  if (existsSync(OUT)) rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
}

let bad = 0;
for (const lang of LANGS) {
  const dict = readJSON(join(SRC, `${lang}.json`), {});
  const keep = noTranslate();
  const missing = [...all.keys()].filter((k) => !keep.has(k) && !resolves(k, dict));
  /* A dictionary entry is live if it is a key, or a part the engine looks up
     while translating one. */
  const live = new Set(all.keys());
  for (const k of all.keys()) for (const t of lookupParts(k)) live.add(t);
  const stale = Object.keys(dict).filter((k) => !live.has(k));
  /* An entry whose translation equals its key renders as English while
     counting as translated — legitimate for a word that is the same in
     both languages, a bug for anything else. Report it so it stays visible. */
  const identical = Object.keys(dict).filter((k) => dict[k] === k && !keep.has(k));
  if (missing.length) bad = 1;
  if (!check) {
    let n = emit(lang, "common", common, dict);
    let pages = 0;
    for (const [slug, keys] of perPage) {
      const c = emit(lang, slug, keys, dict);
      if (c) { n += c; pages++; }
    }
    console.log(`${lang}: ${n} strings → common + ${pages} page files`);
  }
  const translatable = all.size - [...all.keys()].filter((k) => keep.has(k)).length;
  console.log(`${lang}: ${translatable - missing.length}/${translatable} translated` +
    (missing.length ? `  · MISSING ${missing.length}` : "  · complete") +
    (stale.length ? `  · stale ${stale.length}` : "") +
    (identical.length ? `  · identical ${identical.length}` : ""));
}
if (!check) {
  const version = assetVersion();
  const touched = stampVersion(version);
  console.log(`asset version ${version} → ${touched} file(s) stamped`);
}
if (check && bad) process.exit(1);
}
